import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:quisquislingo_app/models/course_flag_selection.dart';
import 'package:quisquislingo_app/models/world_flag_entity.dart';
import 'package:quisquislingo_app/services/course_flag_catalog_service.dart';
import 'package:quisquislingo_app/widgets/course_flag_picker.dart';

void main() {
  testWidgets('picker exposes the required source order and Japanese origins', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(800, 600));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await _openPicker(tester, languageName: 'Japanese', languageTag: 'ja');

    expect(find.text('Current selection'), findsOneWidget);
    expect(find.text('Japanese · QQL FlagPainter Flag'), findsOneWidget);
    expect(find.text('Generated by QQL'), findsWidgets);
    expect(find.text('Use Automatic'), findsOneWidget);
    expect(find.text('Upload custom flag'), findsOneWidget);
    expect(find.byKey(const Key('course-flag-picker-search')), findsOneWidget);
    expect(
      tester
          .widget<TextField>(find.byKey(const Key('course-flag-picker-search')))
          .controller!
          .text,
      'Japanese',
    );
    expect(find.text('Suggested WORLD Flag for Japanese'), findsOneWidget);
    expect(find.text('Japan'), findsOneWidget);
    expect(find.text('QQL FlagPainter Flags'), findsOneWidget);
    expect(find.text('Flags from installed QQL courses'), findsNothing);

    final currentTop = tester.getTopLeft(find.text('Current selection')).dy;
    final automaticTop = tester.getTopLeft(find.text('Use Automatic')).dy;
    final uploadTop = tester.getTopLeft(find.text('Upload custom flag')).dy;
    final searchTop = tester
        .getTopLeft(find.byKey(const Key('course-flag-picker-search')))
        .dy;
    expect(currentTop, lessThan(automaticTop));
    expect(automaticTop, lessThan(uploadTop));
    expect(uploadTop, lessThan(searchTop));

    final scrollable = find.descendant(
      of: find.byKey(const Key('course-flag-picker-results')),
      matching: find.byType(Scrollable),
    );
    await tester.scrollUntilVisible(
      find.text('WORLD Flags'),
      400,
      scrollable: scrollable.first,
    );
    expect(find.text('WORLD Flags'), findsOneWidget);
  });

  testWidgets(
    'small picker has a bounded list and compact non-overlapping Cancel',
    (tester) async {
      await tester.binding.setSurfaceSize(const Size(600, 420));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await _openPicker(tester, languageName: 'Japanese', languageTag: 'jpn');

      expect(tester.takeException(), isNull);
      final results = find.byKey(const Key('course-flag-picker-results'));
      final actions = find.byKey(const Key('course-flag-picker-actions'));
      expect(results, findsOneWidget);
      expect(actions, findsOneWidget);
      expect(tester.getSize(actions).height, lessThanOrEqualTo(72));
      expect(
        tester.getBottomLeft(results).dy,
        lessThanOrEqualTo(tester.getTopLeft(actions).dy),
      );

      await tester.enterText(
        find.byKey(const Key('course-flag-picker-search')),
        '',
      );
      await tester.pumpAndSettle();
      final last = find.byKey(const ValueKey('course-flag-option-world:wales'));
      final scrollable = find.descendant(
        of: results,
        matching: find.byType(Scrollable),
      );
      await tester.scrollUntilVisible(last, 400, scrollable: scrollable.first);
      await tester.pumpAndSettle();
      expect(last, findsOneWidget);
      expect(
        tester.getBottomLeft(last).dy,
        lessThanOrEqualTo(tester.getTopLeft(actions).dy),
      );
      expect(tester.takeException(), isNull);
    },
  );

  testWidgets(
    'WORLD automatic fallback is identified without duplicate suggestion',
    (tester) async {
      await _openPicker(tester, languageName: 'French', languageTag: 'fra');

      expect(find.text('France · WORLD Flag · FR'), findsOneWidget);
      expect(
        find.text('No QQL FlagPainter Flag is available for French.'),
        findsOneWidget,
      );
      expect(find.text('Suggested WORLD Flag for French'), findsNothing);
      expect(find.text('No FlagPainter flag found'), findsOneWidget);
      expect(find.text('No flags found'), findsNothing);
    },
  );

  testWidgets('search starts with the language name without a language code', (
    tester,
  ) async {
    await _openPicker(tester, languageName: 'Welsh (cy)', languageTag: 'cy');

    expect(
      tester
          .widget<TextField>(find.byKey(const Key('course-flag-picker-search')))
          .controller!
          .text,
      'Welsh',
    );
  });
}

Future<void> _openPicker(
  WidgetTester tester, {
  required String languageName,
  required String languageTag,
}) async {
  final catalog = CourseFlagCatalogService().build(
    manifest: _manifest,
    languageName: languageName,
    languageTag: languageTag,
  );
  await tester.pumpWidget(
    MaterialApp(
      home: Builder(
        builder: (context) => TextButton(
          onPressed: () => showCourseFlagPicker(
            context: context,
            currentSelection: const CourseFlagSelection.automatic(),
            languageName: languageName,
            languageTag: languageTag,
            catalogFuture: catalog,
          ),
          child: const Text('Open'),
        ),
      ),
    ),
  );
  await tester.tap(find.text('Open'));
  await tester.pumpAndSettle();
}

const _manifest = WorldFlagManifest(
  entities: [
    WorldFlagEntity(
      id: 'france',
      displayNameEn: 'France',
      assetPath: 'assets/world_flags/flags/france.svg',
      category: WorldFlagCategory.unMember,
      isoAlpha2: 'FR',
      isoAlpha3: 'FRA',
    ),
    WorldFlagEntity(
      id: 'japan',
      displayNameEn: 'Japan',
      assetPath: 'assets/world_flags/flags/japan.svg',
      category: WorldFlagCategory.unMember,
      isoAlpha2: 'JP',
      isoAlpha3: 'JPN',
    ),
    WorldFlagEntity(
      id: 'wales',
      displayNameEn: 'Wales',
      assetPath: 'assets/world_flags/flags/wales.svg',
      category: WorldFlagCategory.shortlist,
      subdivisionCode: 'GB-WLS',
    ),
  ],
);
