import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:quisquislingo_app/models/course_flag_selection.dart';
import 'package:quisquislingo_app/models/world_flag_entity.dart';
import 'package:quisquislingo_app/services/course_flag_catalog_service.dart';
import 'package:quisquislingo_app/services/world_flag_repository.dart';

void main() {
  late WorldFlagManifest manifest;

  setUpAll(() {
    manifest = WorldFlagRepository.parseManifestDocument(
      File('assets/world_flags/manifest.json').readAsStringSync(),
    );
  });

  test('catalog has only complete permanent QQL and WORLD sections', () async {
    final catalog = await CourseFlagCatalogService().build(
      manifest: manifest,
      languageName: 'Japanese',
      languageTag: 'ja-JP',
    );

    expect(
      catalog.sections.map((section) => (section.kind, section.title)).toList(),
      const [
        (CourseFlagCatalogSectionKind.qqlFlagPainter, 'QQL FlagPainter Flags'),
        (CourseFlagCatalogSectionKind.worldFlags, 'WORLD Flags'),
      ],
    );
    expect(catalog.sections.first.candidates, hasLength(10));
    expect(
      catalog.sections.last.candidates,
      hasLength(manifest.entities.length),
    );
    expect(
      catalog.sections.first.candidates
          .map((candidate) => candidate.identity)
          .toSet(),
      hasLength(10),
    );
  });

  test(
    'Japanese automatic source and WORLD alternative are explicit',
    () async {
      final catalog = await CourseFlagCatalogService().build(
        manifest: manifest,
        languageName: 'Japanese',
        languageTag: 'jpn',
      );

      expect(catalog.automaticCandidate?.identity, 'qql-flagpainter-japanese');
      expect(catalog.automaticCandidate?.label, 'Japanese');
      expect(
        catalog.automaticCandidate?.subtitle,
        'QQL FlagPainter Flag · Generated by QQL',
      );
      expect(catalog.suggestedWorldFlag?.identity, 'world:japan');
      expect(catalog.suggestedWorldFlag?.label, 'Japan');
      expect(catalog.suggestedWorldFlag?.subtitle, 'WORLD Flag · JP');
    },
  );

  test('WORLD automatic fallback is not repeated as a suggestion', () async {
    final french = await CourseFlagCatalogService().build(
      manifest: manifest,
      languageName: 'French',
      languageTag: 'fra',
    );
    final unknown = await CourseFlagCatalogService().build(
      manifest: manifest,
      languageName: 'Klingon',
      languageTag: 'tlh',
    );

    expect(french.automaticCandidate?.identity, 'world:france');
    expect(french.suggestedWorldFlag, isNull);
    expect(unknown.automaticCandidate, isNull);
    expect(
      unknown.automaticUnavailableMessage,
      'No automatic flag is available for this language.',
    );
    expect(
      unknown.worldSuggestionUnavailableMessage,
      'No associated WORLD Flag is available for this language.',
    );
  });

  test('Welsh QQL and Wales WORLD entries remain distinct', () async {
    final catalog = await CourseFlagCatalogService().build(
      manifest: manifest,
      languageName: 'Cymraeg',
      languageTag: 'cy-GB',
    );
    final qql = catalog.sections.first.candidates.singleWhere(
      (candidate) => candidate.identity == 'qql-flagpainter-welsh',
    );
    final world = catalog.sections.last.candidates.singleWhere(
      (candidate) => candidate.identity == 'world:wales',
    );

    expect(qql.label, 'Welsh');
    expect(qql.selection, CourseFlagSelection.builtIn('CY'));
    expect(world.label, 'Wales');
    expect(world.subtitle, 'WORLD Flag · GB-WLS');
    expect(catalog.suggestedWorldFlag?.identity, 'world:wales');
  });

  test('search covers QQL IDs, aliases and language codes', () async {
    final catalog = await CourseFlagCatalogService().build(
      manifest: manifest,
      languageName: 'Unknown',
      languageTag: 'und',
    );

    expect(
      catalog.search('qql-flagpainter-japanese').single.candidates.single.label,
      'Japanese',
    );
    expect(
      catalog
          .search('Nihongo')
          .expand((section) => section.candidates)
          .map((candidate) => candidate.identity),
      containsAll(['qql-flagpainter-japanese', 'world:japan']),
    );
    expect(
      catalog
          .search('jpn')
          .expand((section) => section.candidates)
          .map((candidate) => candidate.identity),
      containsAll(['qql-flagpainter-japanese', 'world:japan']),
    );
    expect(
      catalog.search('GB-WLS').single.candidates.single.identity,
      'world:wales',
    );
  });
}
