/// Audit severities retain their established validation meaning.
enum AuditSeverity { error, warning, info }

/// Stable definitions for every known production Audit rule.
///
/// The enum is also the complete reference inventory: service findings, Help
/// and tests use these same values. GENERAL is deliberately not a production
/// rule; the legacy issue constructor reserves it for unexpected findings.
enum AuditCode {
  idMissing(
    'ID_MISSING',
    AuditSeverity.error,
    'Course, Lesson, Duel, Round, Content',
    'An audited object has no stable identity.',
    'A course, Lesson, Duel, Round or Content ID is empty after trimming.',
    'Repair the missing ID using the authoring tools; keep valid existing IDs unchanged.',
  ),
  idDuplicate(
    'ID_DUPLICATE',
    AuditSeverity.error,
    'Course, Lesson, Duel, Round, Content',
    'Two audited objects share the same stable ID.',
    'An ID repeats within the course-wide audited identity set.',
    'Use Copy or Duplicate to create an independent object with fresh IDs; repair references when correcting imported data.',
  ),
  courseLanguagesRequired(
    'COURSE_LANGUAGES_REQUIRED',
    AuditSeverity.error,
    'Course',
    'The course language pair is incomplete.',
    'Source language or target language is empty after trimming.',
    'Choose both source and target languages in Course Info.',
  ),
  courseLanguagesIdentical(
    'COURSE_LANGUAGES_IDENTICAL',
    AuditSeverity.warning,
    'Course',
    'The source and target language names are the same.',
    'The two stored language names match when case is ignored.',
    'Check that the course language pair is intentional.',
  ),
  courseAuthorsMany(
    'COURSE_AUTHORS_MANY',
    AuditSeverity.warning,
    'Course Info',
    'The author list may contain accidental duplicates.',
    'The course has more than 50 author entries.',
    'Review the author list and remove only accidental duplicates.',
  ),
  courseAuthorEmpty(
    'COURSE_AUTHOR_EMPTY',
    AuditSeverity.warning,
    'Course Info',
    'An author entry has no name.',
    'An author name is empty after trimming.',
    'Enter the credited author name or remove the unused entry.',
  ),
  courseAuthorLong(
    'COURSE_AUTHOR_LONG',
    AuditSeverity.warning,
    'Course Info',
    'An author name or role may be difficult to display.',
    'An author name or any role exceeds 120 characters.',
    'Check the credit for pasted text or unintended length.',
  ),
  courseAuthorRoleEmpty(
    'COURSE_AUTHOR_ROLE_EMPTY',
    AuditSeverity.warning,
    'Course Info',
    'An author entry has no contributor role.',
    'An author has zero roles.',
    'Choose at least one appropriate role, such as Contributor.',
  ),
  courseAuthorRolesMany(
    'COURSE_AUTHOR_ROLES_MANY',
    AuditSeverity.warning,
    'Course Info',
    'An author has an unusually large role list.',
    'An author has more than 12 roles.',
    'Review roles for accidental duplicates.',
  ),
  courseDescriptionLong(
    'COURSE_DESCRIPTION_LONG',
    AuditSeverity.warning,
    'Course Info',
    'The course description may be difficult to edit or display.',
    'The description exceeds 5,000 characters.',
    'Shorten the description if the length is unintended.',
  ),
  courseLessonsEmpty(
    'COURSE_LESSONS_EMPTY',
    AuditSeverity.warning,
    'Course',
    'The course has no Lessons yet.',
    'The Lesson list is empty.',
    'Add Lessons when ready; an empty course is supported during authoring.',
  ),
  audioMappingTextEmpty(
    'AUDIO_MAPPING_TEXT_EMPTY',
    AuditSeverity.warning,
    'Audio Library',
    'A recorded MP3 has no associated word or expression.',
    'An Audio Library clip has empty mapping text after trimming.',
    'Associate the recording with the exact intended word or expression.',
  ),
  audioMappingDuplicate(
    'AUDIO_MAPPING_DUPLICATE',
    AuditSeverity.error,
    'Audio Library',
    'More than one recording maps to the same text.',
    'Recorded-audio mapping text repeats after trimming and ignoring case.',
    'Keep one intended recording per mapping text.',
  ),
  recordedAudioLibraryEmpty(
    'RECORDED_AUDIO_LIBRARY_EMPTY',
    AuditSeverity.error,
    'Audio Library',
    'Recorded MP3 mode has no available recordings.',
    'Audio mode is recorded and the Audio Library is empty.',
    'Add the required recordings or choose the intended supported audio mode.',
  ),
  lessonIconAssetIdDuplicate(
    'LESSON_ICON_ASSET_ID_DUPLICATE',
    AuditSeverity.error,
    'Course assets',
    'Managed Lesson icon identities are duplicated.',
    'Two managed Lesson icon assets have the same assetId.',
    'Reimport the icon through the managed icon workflow and repair the duplicate asset identity.',
  ),
  lessonIconAssetInvalid(
    'LESSON_ICON_ASSET_INVALID',
    AuditSeverity.error,
    'Course assets',
    'A managed Lesson icon fails canonical PNG validation.',
    'The embedded icon fails Base64, PNG header or 256 by 256 canvas validation.',
    'Reimport a valid image using the custom Lesson icon importer; follow the detailed error in the finding.',
  ),
  lessonSectionNameRequired(
    'LESSON_SECTION_NAME_REQUIRED',
    AuditSeverity.error,
    'Lesson',
    'A Lesson is marked as belonging to a Section without a name.',
    'Belongs to a Section is enabled and its name is absent or blank.',
    'Enter the intended Section name or disable Belongs to a Section.',
  ),
  lessonSectionNameWithoutSection(
    'LESSON_SECTION_NAME_WITHOUT_SECTION',
    AuditSeverity.error,
    'Lesson',
    'A Section name remains on an unsectioned Lesson.',
    'Belongs to a Section is disabled but a nonblank Section name remains.',
    'Clear the Section name or enable Belongs to a Section.',
  ),
  lessonThemeIconInvalid(
    'LESSON_THEME_ICON_INVALID',
    AuditSeverity.error,
    'Lesson',
    'The Lesson icon reference cannot resolve through an approved source.',
    'The reference is neither a preinstalled icon nor a managed icon ID present in the course.',
    'Choose a preinstalled icon or reimport and select a managed Course-owned icon.',
  ),
  lessonGuidebookEmpty(
    'LESSON_GUIDEBOOK_EMPTY',
    AuditSeverity.warning,
    'Lesson Guidebook',
    'The Lesson has no Guidebook Content.',
    'The Guidebook Content list is empty.',
    'Add vocabulary, examples or explanations before generating Rounds from the Guidebook.',
  ),
  lessonRoundsEmpty(
    'LESSON_ROUNDS_EMPTY',
    AuditSeverity.warning,
    'Lesson',
    'The Lesson has no Rounds yet.',
    'The Round list is empty.',
    'Add Rounds when the Lesson is ready for exercises.',
  ),
  lessonRoundGuidance(
    'LESSON_ROUND_GUIDANCE',
    AuditSeverity.info,
    'Lesson',
    'The Lesson has fewer Rounds than the current Audit guidance suggests.',
    'The Lesson has fewer than 3 Rounds.',
    'Review the Lesson structure; this guidance does not require extra Rounds to save or publish.',
  ),
  lessonIntroMissing(
    'LESSON_INTRO_MISSING',
    AuditSeverity.info,
    'Lesson, first Round',
    'The first Round has no designated Lesson introduction.',
    'The Lesson has Rounds and its first Round has no Content with role lesson_intro.',
    'Consider a short introduction drawn from the Guidebook if useful for learners.',
  ),
  roundContentEmpty(
    'ROUND_CONTENT_EMPTY',
    AuditSeverity.error,
    'Round',
    'The Round has no playable or presentational Content.',
    'The Round Content list is empty.',
    'Add reviewed Content or keep the unfinished Round as Draft where supported.',
  ),
  roundContentLong(
    'ROUND_CONTENT_LONG',
    AuditSeverity.warning,
    'Round',
    'The Round has more than 10 Content items and may need a pacing review.',
    'The Round has more than 10 Content items.',
    'Review pacing; this Warning is not a fixed maximum.',
  ),
  instructionLanguageMismatch(
    'INSTRUCTION_LANGUAGE_MISMATCH',
    AuditSeverity.warning,
    'Exercise in Course',
    'A recognized stock instruction appears to use the wrong language.',
    'A known legacy instruction phrase has a language different from the course source language.',
    'Write the learner instruction in the course source language.',
  ),
  oppositeTooEarly(
    'OPPOSITE_TOO_EARLY',
    AuditSeverity.warning,
    'Exercise in Lesson',
    'An opposites exercise appears early in a Lesson.',
    'One of the first two Rounds contains an exercise matched by the existing opposites prompt heuristic.',
    'Check whether the learner has enough vocabulary before this exercise.',
  ),
  singleWordCase(
    'SINGLE_WORD_CASE',
    AuditSeverity.info,
    'Exercise in Course',
    'An isolated word may have unintended initial capitalization.',
    'For a non-German target course, a single-word prompt, question or answer matches an uppercase initial followed by letters.',
    'Use lowercase unless the language, a proper name or another linguistic reason requires capitalization.',
  ),
  roundDuplicateContent(
    'ROUND_DUPLICATE_CONTENT',
    AuditSeverity.warning,
    'Exercise in Round',
    'The same exercise prompt and question appear repeatedly.',
    'The exercise type, trimmed prompt and trimmed question repeat in a Round when case is ignored.',
    'Check whether the repetition is intentional and useful.',
  ),
  duelUnavailable(
    'DUEL_UNAVAILABLE',
    AuditSeverity.info,
    'Lesson Duel',
    'The Lesson does not currently have a sufficient eligible Duel pool.',
    'The authoritative Duel eligibility service reports the Lesson unavailable.',
    'Review the actual eligible pool if a Duel is intended; unavailable Duels are supported and require no duplicate filler.',
  ),
  sourceRefMissing(
    'SOURCE_REF_MISSING',
    AuditSeverity.error,
    'Content',
    'A source reference points to an ID absent from the course audit identity set.',
    'A Guidebook or Round Content sourceRefs entry is not found among audited IDs.',
    'Repair or remove the broken source reference while preserving valid stable IDs.',
  ),
  wordBlockLanguageMismatch(
    'WORD_BLOCK_LANGUAGE_MISMATCH',
    AuditSeverity.error,
    'Exercise: Word Blocks',
    'A distractor is confidently recognized as a different language from the answer.',
    'Word-order answer blocks identify one supported language and an extra block unambiguously identifies another.',
    'Replace the distractor with a suitable block in the answer language; ambiguous vocabulary is left to human review.',
  ),
  exerciseTypeUnknown(
    'EXERCISE_TYPE_UNKNOWN',
    AuditSeverity.error,
    'Exercise',
    'The exercise type is unsupported.',
    'The runtime type is outside the supported exercise type set.',
    'Use a supported authoring preset; do not invent a new runtime type in imported data.',
  ),
  exercisePresetUnknown(
    'EXERCISE_PRESET_UNKNOWN',
    AuditSeverity.error,
    'Exercise',
    'No supported authoring preset can be resolved.',
    'Neither the editor template nor the runtime-type fallback resolves in the preset registry.',
    'Choose a supported preset or correct the invalid preset identity in the source data.',
  ),
  presetCanonicalMismatch(
    'PRESET_CANONICAL_MISMATCH',
    AuditSeverity.error,
    'Exercise',
    'The response configuration does not match the selected preset.',
    'A non-Presentation preset has an interaction kind different from its canonical model.',
    'Use the response fields belonging to the selected preset; repair inconsistent imported data.',
  ),
  promptMediaUnsupported(
    'PROMPT_MEDIA_UNSUPPORTED',
    AuditSeverity.error,
    'Exercise prompt',
    'A prompt element uses unsupported media.',
    'A prompt element type is outside text, audio and image.',
    'Use supported prompt media through the editor.',
  ),
  exerciseItemIds(
    'EXERCISE_ITEM_IDS',
    AuditSeverity.error,
    'Exercise Items',
    'Response Items do not have unique nonempty IDs.',
    'An Item ID is blank or repeated within the interaction.',
    'Repair Item identities and their answer references together; use authoritative Copy for independent exercises.',
  ),
  exerciseItemReference(
    'EXERCISE_ITEM_REFERENCE',
    AuditSeverity.error,
    'Exercise evaluation',
    'Evaluation points to an Item absent from the response configuration.',
    'A correct Item, ordered-answer Item or pair reference does not occur in the interaction Item set.',
    'Reselect the correct options, rebuild the correct order or repair the pair references.',
  ),
  exerciseTextLong(
    'EXERCISE_TEXT_LONG',
    AuditSeverity.warning,
    'Exercise',
    'Prompt or question text may be difficult to read on a small screen.',
    'Prompt length exceeds 1,200 characters or question length exceeds 800.',
    'Review the text at narrow learner widths and shorten it if appropriate.',
  ),
  exerciseFieldUnexpected(
    'EXERCISE_FIELD_UNEXPECTED',
    AuditSeverity.warning,
    'Exercise',
    'Independent stored data do not belong to the selected preset.',
    'Correct options, accepted answers, orders, pairs, hints, missing words or icons remain where the runtime preset does not expect that field.',
    'Review the named field and remove only unintended stale data.',
  ),
  choiceAnswersRequired(
    'CHOICE_ANSWERS_REQUIRED',
    AuditSeverity.error,
    'Exercise: Select',
    'The learner has too few answer options.',
    'A choice-based exercise has fewer than 2 answers.',
    'Enter at least two nonblank options and select the correct answer.',
  ),
  dialogueResponseOptionCount(
    'DIALOGUE_RESPONSE_OPTION_COUNT',
    AuditSeverity.error,
    'Exercise: Dialogue Response',
    'The response choice count is not supported.',
    'Dialogue Response has a number of options other than 2.',
    'Enter exactly two response options.',
  ),
  dialogueContextRequired(
    'DIALOGUE_CONTEXT_REQUIRED',
    AuditSeverity.error,
    'Exercise: Dialogue Response',
    'The dialogue situation is missing.',
    'The context prompt is blank.',
    'Enter a context sentence explaining the situation.',
  ),
  dialogueQuestionRequired(
    'DIALOGUE_QUESTION_REQUIRED',
    AuditSeverity.error,
    'Exercise: Dialogue Response',
    'The dialogue question is missing.',
    'The question is blank.',
    'Enter the question the learner should answer.',
  ),
  choiceCorrectAnswerInvalid(
    'CHOICE_CORRECT_ANSWER_INVALID',
    AuditSeverity.error,
    'Exercise: Select',
    'No valid correct option is selected.',
    'The resolved correct-answer index is absent, negative or outside the answer list.',
    'Choose a correct answer from the current visible options.',
  ),
  choiceAnswerEmpty(
    'CHOICE_ANSWER_EMPTY',
    AuditSeverity.error,
    'Exercise: Select',
    'An answer option is blank.',
    'Any option is empty after trimming.',
    'Enter meaningful text for every answer option.',
  ),
  choiceAnswerDuplicate(
    'CHOICE_ANSWER_DUPLICATE',
    AuditSeverity.warning,
    'Exercise: Select',
    'Answer options repeat.',
    'Options are duplicated after trimming and ignoring case.',
    'Use distinct options or review any intentional equivalence.',
  ),
  placeholderAnswer(
    'PLACEHOLDER_ANSWER',
    AuditSeverity.error,
    'Exercise: Select',
    'An option contains known dummy answer text.',
    'An option equals xyz, abc, placeholder, test answer or dummy after trimming and ignoring case.',
    'Replace the placeholder with reviewed course content or a real distractor.',
  ),
  translationPromptMissingSource(
    'TRANSLATION_PROMPT_MISSING_SOURCE',
    AuditSeverity.error,
    'Exercise: Select translation',
    'A stock translation instruction does not identify what to translate.',
    'The prompt is only the recognized English or Spanish choose-the-correct-translation instruction.',
    'Include the actual source word or expression in the prompt.',
  ),
  correctItemUnresolved(
    'CORRECT_ITEM_UNRESOLVED',
    AuditSeverity.error,
    'Exercise: Select',
    'A stored correct Item reference does not resolve to a visible option.',
    'Correct Item IDs are present but no visible correct-answer index resolves.',
    'Reselect the correct answer from the available options and inspect broken Item references.',
  ),
  readingOptionNotInPassage(
    'READING_OPTION_NOT_IN_PASSAGE',
    AuditSeverity.warning,
    'Exercise: Reading comprehension',
    'A generated vocabulary question may not match its passage.',
    'The recognized generated vocabulary question has a valid correct option whose nonempty text is absent from the passage, ignoring case.',
    'Review the passage, question and correct option together; do not force an unrelated answer into the passage.',
  ),
  listeningAudioRequired(
    'LISTENING_AUDIO_REQUIRED',
    AuditSeverity.error,
    'Exercise: Listening, Missing Word',
    'Required listening audio text is absent.',
    'A listening-prefixed preset or Missing Word has empty or absent TTS/audio text.',
    'Enter the text used by the supported audio mechanism; an exercise must supply its own required listening content.',
  ),
  gapSentenceRequired(
    'GAP_SENTENCE_REQUIRED',
    AuditSeverity.error,
    'Exercise: Gap Choice',
    'The sentence containing the gap is missing.',
    'The target-language sentence is empty after trimming.',
    'Enter the sentence and mark its gap with ___.',
  ),
  gapMarkerMissing(
    'GAP_MARKER_MISSING',
    AuditSeverity.error,
    'Exercise: Gap Choice',
    'The sentence has no recognized gap marker.',
    'The sentence contains zero occurrences of ___.',
    'Use ___ at the position the learner should complete.',
  ),
  gapMarkerCount(
    'GAP_MARKER_COUNT',
    AuditSeverity.warning,
    'Exercise: Gap Choice',
    'The sentence contains more than one gap marker.',
    'The sentence contains more than one occurrence of ___.',
    'Normally use one gap; review whether the extra marker is accidental.',
  ),
  gapSentenceTooShort(
    'GAP_SENTENCE_TOO_SHORT',
    AuditSeverity.error,
    'Exercise: Gap Choice',
    'Completing the gap does not produce a sentence of at least two words.',
    'A valid nonempty correct answer replaces the first gap and the result has fewer than 2 lexical words.',
    'Write a complete sentence around the gap.',
  ),
  listeningSpellingNoAnswer(
    'LISTENING_SPELLING_NO_ANSWER',
    AuditSeverity.error,
    'Exercise: Listening Spelling',
    'There is no text answer to evaluate.',
    'The accepted-answer list is empty.',
    'Enter at least one accepted transcription.',
  ),
  answerExpressionInvalid(
    'ANSWER_EXPRESSION_INVALID',
    AuditSeverity.error,
    'Exercise: accepted answers',
    'An authored answer expression cannot be expanded.',
    'The authoritative parser rejects an individual accepted expression for Fill-in, Listening Spelling or Type the translation.',
    'Correct the syntax or expansion problem described by the parser; keep each intended answer explicit when simpler.',
  ),
  answerExpansionLimit(
    'ANSWER_EXPANSION_LIMIT',
    AuditSeverity.error,
    'Exercise: accepted answers',
    'The complete accepted-answer set cannot be expanded.',
    'Expanding all accepted expressions raises a parser exception, including combined expansion overflow or invalid syntax.',
    'Resolve the detailed parser error and keep the whole expanded set within the authoritative limit.',
  ),
  translationSourceRequired(
    'TRANSLATION_SOURCE_REQUIRED',
    AuditSeverity.error,
    'Exercise: Type the translation',
    'There is no source text to translate.',
    'The source prompt is blank.',
    'Enter the source-language word or sentence.',
  ),
  translationAnswerRequired(
    'TRANSLATION_ANSWER_REQUIRED',
    AuditSeverity.error,
    'Exercise: Type the translation',
    'No accepted translation is defined.',
    'The accepted-answer list is empty.',
    'Enter at least one accepted translation using supported answer syntax.',
  ),
  contextQuestionRequired(
    'CONTEXT_QUESTION_REQUIRED',
    AuditSeverity.error,
    'Exercise: Contextual comprehension',
    'The exercise has no separate question.',
    'The question field is blank.',
    'Enter the question about the context separately from the context itself.',
  ),
  contextRequired(
    'CONTEXT_REQUIRED',
    AuditSeverity.error,
    'Exercise: Contextual comprehension',
    'There is no context for the question.',
    'Context text and audio are blank and no dialogue turns exist.',
    'Provide text context, audio context or structured dialogue.',
  ),
  dialogueTurnInvalid(
    'DIALOGUE_TURN_INVALID',
    AuditSeverity.error,
    'Exercise: Contextual comprehension',
    'A dialogue turn has incomplete speaker or text information.',
    'Any dialogue turn has a blank speaker or blank text.',
    'Enter both a speaker label and spoken text for every turn.',
  ),
  missingWordTranscriptRequired(
    'MISSING_WORD_TRANSCRIPT_REQUIRED',
    AuditSeverity.error,
    'Exercise: Missing Word',
    'The listening passage has no transcript.',
    'The transcript prompt is blank.',
    'Enter the passage transcript containing the words to remove.',
  ),
  missingWordAnswerRequired(
    'MISSING_WORD_ANSWER_REQUIRED',
    AuditSeverity.error,
    'Exercise: Missing Word',
    'No words have been selected for removal.',
    'The missing-word list is empty.',
    'Enter at least one word that occurs in the transcript.',
  ),
  missingWordNotInTranscript(
    'MISSING_WORD_NOT_IN_TRANSCRIPT',
    AuditSeverity.error,
    'Exercise: Missing Word',
    'A requested missing word does not occur in the transcript.',
    'The transcript does not contain a listed missing word when case is ignored.',
    'Correct the word or transcript so the intended missing word occurs in the passage.',
  ),
  missingWordDuplicate(
    'MISSING_WORD_DUPLICATE',
    AuditSeverity.warning,
    'Exercise: Missing Word',
    'The missing-word list repeats an entry.',
    'Entries repeat after trimming and ignoring case.',
    'Remove accidental duplicate entries and review the intended omissions.',
  ),
  readingPassageRequired(
    'READING_PASSAGE_REQUIRED',
    AuditSeverity.error,
    'Exercise: Reading comprehension',
    'An existing Reading exercise has no passage containing words.',
    'The Reading passage has zero lexical words or numbers.',
    'Enter an actual Reading passage; punctuation alone is insufficient.',
  ),
  readingPassageTooShort(
    'READING_PASSAGE_TOO_SHORT',
    AuditSeverity.warning,
    'Exercise: Reading comprehension',
    'An existing Reading passage may be too short for comprehension.',
    'The Reading passage has 1 or 2 lexical words or numbers.',
    'Consider a passage of at least three words that supports its question.',
  ),
  listeningPassageShort(
    'LISTENING_PASSAGE_SHORT',
    AuditSeverity.info,
    'Exercise: Listening comprehension',
    'An existing listening passage is very short.',
    'The trimmed audio text splits into fewer than 5 whitespace-separated entries.',
    'Check that the passage tests comprehension; absence of a Listening exercise in a Round is not a finding.',
  ),
  fillBlankAnswerRequired(
    'FILL_BLANK_ANSWER_REQUIRED',
    AuditSeverity.error,
    'Exercise: Fill-in',
    'No accepted response is defined.',
    'The accepted-answer list is empty.',
    'Enter at least one accepted answer.',
  ),
  wordBlockDataRequired(
    'WORD_BLOCK_DATA_REQUIRED',
    AuditSeverity.error,
    'Exercise: Arrange',
    'The available blocks or correct answer orders are absent.',
    'Word Blocks, Image Word or Build the translation has no available blocks or no correctOrders.',
    'Provide available blocks and at least one complete literal correct answer with its ordered blocks.',
  ),
  buildTranslationAnswerRequired(
    'BUILD_TRANSLATION_ANSWER_REQUIRED',
    AuditSeverity.error,
    'Exercise: Arrange',
    'A correct ordered answer has no usable literal text.',
    'An ordered answer becomes empty after trimming, whitespace normalization and terminal sentence-punctuation removal.',
    'Enter a complete nonempty literal answer that the selected block order constructs.',
  ),
  buildTranslationDuplicateAnswer(
    'BUILD_TRANSLATION_DUPLICATE_ANSWER',
    AuditSeverity.error,
    'Exercise: Arrange',
    'Correct ordered answers are equivalent after normalization.',
    'Two answers match after ignoring case, repeated whitespace and terminal sentence punctuation.',
    'Remove the duplicate answer; keep distinct literal answers in their authored order.',
  ),
  buildTranslationInvalidSequence(
    'BUILD_TRANSLATION_INVALID_SEQUENCE',
    AuditSeverity.error,
    'Exercise: Arrange',
    'A correct answer has an empty or broken block sequence.',
    'An ordered answer has no Item IDs or references an Item absent from the available blocks.',
    'Select the blocks for that answer in the intended order using existing block occurrences.',
  ),
  buildTranslationReusedBlock(
    'BUILD_TRANSLATION_REUSED_BLOCK',
    AuditSeverity.error,
    'Exercise: Arrange',
    'A correct answer tries to use one block occurrence more than once.',
    'An ordered answer repeats the same Item ID.',
    'Add a separate available block occurrence for each repeated word and use each occurrence once.',
  ),
  buildTranslationUnconstructable(
    'BUILD_TRANSLATION_UNCONSTRUCTABLE',
    AuditSeverity.error,
    'Exercise: Arrange',
    'The ordered blocks do not literally construct the answer text.',
    'Joining the referenced block values differs from the answer after the established case, whitespace and terminal-punctuation normalization; Image Word joins without spaces.',
    'Make the answer text and selected block order agree; include every required word, letter or syllable.',
  ),
  wordBlockDistractorCount(
    'WORD_BLOCK_DISTRACTOR_COUNT',
    AuditSeverity.error,
    'Exercise: Arrange',
    'Too many unused blocks remain.',
    'Image Word has any unused block; Word Blocks has more than 2 outside its first answer; Build the translation has more than 2 unused by every correct answer.',
    'Remove extra blocks. Image Word permits no extras; Word Blocks and Build the translation permit 0, 1 or 2 distractors.',
  ),
  flashcardTextRequired(
    'FLASHCARD_TEXT_REQUIRED',
    AuditSeverity.error,
    'Exercise: Flashcard',
    'The Flashcard has no target word or phrase.',
    'The prompt is blank.',
    'Enter the target-language word or phrase.',
  ),
  flashcardMeaningEmpty(
    'FLASHCARD_MEANING_EMPTY',
    AuditSeverity.warning,
    'Exercise: Flashcard',
    'The Flashcard has no meaning text.',
    'The meaning/question is blank.',
    'Add the meaning if appropriate for this Flashcard.',
  ),
  flashcardExampleEmpty(
    'FLASHCARD_EXAMPLE_EMPTY',
    AuditSeverity.warning,
    'Exercise: Flashcard',
    'The Flashcard has no usage example.',
    'The answer/example list is empty or its first entry is blank.',
    'Add a useful usage sentence.',
  ),
  flashcardAudioEmpty(
    'FLASHCARD_AUDIO_EMPTY',
    AuditSeverity.warning,
    'Exercise: Flashcard',
    'The Flashcard has no pronunciation text.',
    'TTS text is absent or blank.',
    'Add the intended pronunciation text if audio is useful.',
  ),
  matchingPairsRequired(
    'MATCHING_PAIRS_REQUIRED',
    AuditSeverity.error,
    'Exercise: Matching',
    'There are no pairs to match.',
    'The Matching pair list is empty.',
    'Enter at least one meaningful pair.',
  ),
  audioMatchPairCount(
    'AUDIO_MATCH_PAIR_COUNT',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'The sound/text pair count is unsupported.',
    'Audio Match has a number of pairs other than 3.',
    'Enter exactly three sound/text pairs.',
  ),
  audioMatchAnswerCount(
    'AUDIO_MATCH_ANSWER_COUNT',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'The visible answer list does not match the sound count.',
    'The number of visible answers differs from the number of pairs.',
    'Provide one visible matching answer for each sound with no distractors.',
  ),
  audioMatchAnswerDuplicate(
    'AUDIO_MATCH_ANSWER_DUPLICATE',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'Visible matching choices repeat.',
    'Visible answers repeat after trimming and ignoring case.',
    'Use distinct visible matching choices.',
  ),
  audioMatchPairEmpty(
    'AUDIO_MATCH_PAIR_EMPTY',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'A sound/text pair is incomplete.',
    'Either value in a two-entry pair is blank.',
    'Enter both sound text and matching text for each pair.',
  ),
  audioMatchAnswerMissing(
    'AUDIO_MATCH_ANSWER_MISSING',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'A pair refers to a matching answer absent from the visible choices.',
    'A pair right-side value is absent from visible answers after trimming and ignoring case.',
    'Include the pair matching value in the visible choices.',
  ),
  audioMatchSoundDuplicate(
    'AUDIO_MATCH_SOUND_DUPLICATE',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'Two pairs use the same normalized sound text.',
    'Sound text repeats after ignoring case and punctuation and collapsing whitespace.',
    'Give each pair distinct target audio text.',
  ),
  audioMatchTextDuplicate(
    'AUDIO_MATCH_TEXT_DUPLICATE',
    AuditSeverity.error,
    'Exercise: Audio Match',
    'Two pairs use the same normalized matching text.',
    'Matching text repeats after ignoring case and punctuation and collapsing whitespace.',
    'Give each pair distinct matching text.',
  ),
  matchPairCount(
    'MATCH_PAIR_COUNT',
    AuditSeverity.error,
    'Exercise: Word Match, Super Match',
    'The pair count is unsupported.',
    'Word Match or Super Match has a number of pairs other than 3.',
    'Enter exactly three pairs.',
  ),
  matchPairEmpty(
    'MATCH_PAIR_EMPTY',
    AuditSeverity.error,
    'Exercise: Word Match, Super Match',
    'A pair is incomplete.',
    'Either value in a two-entry pair is blank.',
    'Enter both the left and right values for every pair.',
  ),
  matchLeftDuplicate(
    'MATCH_LEFT_DUPLICATE',
    AuditSeverity.error,
    'Exercise: Word Match, Super Match',
    'Left-side items are not distinct.',
    'Two valid pairs have equal left values after ignoring case and punctuation and collapsing whitespace.',
    'Use a distinct left-side value for each pair.',
  ),
  matchRightDuplicate(
    'MATCH_RIGHT_DUPLICATE',
    AuditSeverity.error,
    'Exercise: Word Match, Super Match',
    'Right-side items are not distinct.',
    'Two valid pairs have equal right values after ignoring case and punctuation and collapsing whitespace.',
    'Use a distinct right-side value for each pair.',
  ),
  imageWordImageRequired(
    'IMAGE_WORD_IMAGE_REQUIRED',
    AuditSeverity.error,
    'Exercise: Image Word',
    'The word-building exercise has no image.',
    'The image reference is blank.',
    'Select an image supported by the image authoring workflow.',
  ),
  imageWordAnswerRequired(
    'IMAGE_WORD_ANSWER_REQUIRED',
    AuditSeverity.error,
    'Exercise: Image Word',
    'There is no correct target word order.',
    'The projected correct order is empty.',
    'Enter the target-language word and select its letter or syllable blocks in order.',
  ),
  imageWordAnswerBlank(
    'IMAGE_WORD_ANSWER_BLANK',
    AuditSeverity.error,
    'Exercise: Image Word',
    'The correct target word contains no text.',
    'Joining the projected answer blocks produces blank text.',
    'Enter nonblank letter or syllable blocks that form the target word.',
  ),
  iconChoiceCount(
    'ICON_CHOICE_COUNT',
    AuditSeverity.error,
    'Exercise: Icon Choice',
    'The icon list does not match the answer list.',
    'The number of projected icons differs from the number of answers.',
    'Assign an icon for each answer option and repair inconsistent option data.',
  ),
  hintRepeatsPrompt(
    'HINT_REPEATS_PROMPT',
    AuditSeverity.warning,
    'Exercise Hint',
    'The Hint repeats context instead of helping.',
    'The Hint equals nonempty prompt, question, context text or context audio after the established edge-punctuation and case normalization.',
    'Write a useful clue that adds information without revealing the answer.',
  ),
  hintRevealsAnswer(
    'HINT_REVEALS_ANSWER',
    AuditSeverity.error,
    'Exercise Hint',
    'The Hint directly reveals an authored correct answer.',
    'The Hint equals a stored accepted answer, ordered-answer text or selected correct Item value after the established edge-punctuation and case normalization.',
    'Replace the Hint with a clue that does not state a correct answer.',
  );

  const AuditCode(
    this.code,
    this.severity,
    this.scope,
    this.meaning,
    this.trigger,
    this.creatorAction,
  );

  final String code;
  final AuditSeverity severity;
  final String scope;
  final String meaning;
  final String trigger;
  final String creatorAction;

  bool get blocking => severity == AuditSeverity.error;
  String get severityLabel => switch (severity) {
    AuditSeverity.error => 'Error',
    AuditSeverity.warning => 'Warning',
    AuditSeverity.info => 'Info',
  };
}

abstract final class AuditCodeRegistry {
  static List<AuditCode> get definitions => AuditCode.values;

  static AuditCode? byCode(String code) {
    for (final definition in definitions) {
      if (definition.code == code) return definition;
    }
    return null;
  }

  /// Search every documented field; all terms must occur, in any order.
  static List<AuditCode> search(String query) {
    final terms = query.trim().toLowerCase().split(RegExp(r'\s+'));
    return definitions
        .where((definition) {
          final text = [
            definition.code,
            definition.severityLabel,
            definition.scope,
            definition.meaning,
            definition.trigger,
            definition.creatorAction,
            'Blocking: ${definition.blocking ? 'Yes' : 'No'}',
          ].join(' ').toLowerCase();
          return terms.every(text.contains);
        })
        .toList(growable: false);
  }
}
