import '../models/course_flag_selection.dart';
import '../models/world_flag_entity.dart';
import 'language_flag_catalog.dart';
import 'world_flag_repository.dart';

/// Builds the two permanent Course Flag catalogs.
///
/// Neither catalog depends on installed, bundled, imported or custom Courses.
class CourseFlagCatalogService {
  final WorldFlagRepository _worldFlags;

  CourseFlagCatalogService({WorldFlagRepository? worldFlagRepository})
    : _worldFlags = worldFlagRepository ?? WorldFlagRepository();

  Future<CourseFlagCatalog> build({
    required String languageName,
    String? languageTag,
    WorldFlagManifest? manifest,
  }) async {
    final loadedManifest = manifest ?? await _worldFlags.loadManifest();
    final worldById = {
      for (final entity in loadedManifest.entities) entity.id: entity,
    };

    final qqlCandidates = <CourseFlagCandidate>[
      for (final flag in LanguageFlagCatalog.qqlFlagPainterFlags)
        CourseFlagCandidate(
          identity: flag.id,
          selection: CourseFlagSelection.builtIn(flag.painterCode),
          label: flag.displayName,
          subtitle: 'QQL FlagPainter Flag · Generated by QQL',
          searchTerms: List.unmodifiable(flag.searchTerms),
        ),
    ];

    final languageSearchTermsByWorldId = <String, Set<String>>{};
    for (final association in LanguageFlagCatalog.worldAssociations) {
      for (final worldFlagId in association.worldFlagIds) {
        languageSearchTermsByWorldId
            .putIfAbsent(worldFlagId, () => <String>{})
            .addAll(association.searchTerms);
      }
    }
    for (final suggestion in loadedManifest.languageSuggestions) {
      for (final worldFlagId in suggestion.worldFlagIds) {
        languageSearchTermsByWorldId
            .putIfAbsent(worldFlagId, () => <String>{})
            .addAll([suggestion.languageTag, ...suggestion.languageNames]);
      }
    }

    final worldCandidates = <CourseFlagCandidate>[
      for (final entity in loadedManifest.entities)
        CourseFlagCandidate(
          identity: 'world:${entity.id}',
          selection: CourseFlagSelection.worldFlag(entity.id),
          label: entity.displayNameEn,
          subtitle: _worldSubtitle(entity),
          searchTerms: <String>[
            entity.id,
            ...entity.aliases,
            if (entity.isoAlpha2 != null) entity.isoAlpha2!,
            if (entity.isoAlpha3 != null) entity.isoAlpha3!,
            if (entity.subdivisionCode != null) entity.subdivisionCode!,
            ...?languageSearchTermsByWorldId[entity.id],
          ],
          worldFlag: entity,
        ),
    ];

    final qqlFlag = LanguageFlagCatalog.qqlFlagFor(
      languageTag: languageTag,
      languageName: languageName,
    );
    final primaryWorldId = LanguageFlagCatalog.primaryWorldFlagId(
      languageTag: languageTag,
      languageName: languageName,
    );
    final primaryWorld = primaryWorldId == null
        ? null
        : worldById[primaryWorldId];
    if (primaryWorldId != null && primaryWorld == null) {
      throw StateError(
        'Primary WORLD Flag "$primaryWorldId" is not present in the manifest.',
      );
    }

    CourseFlagCandidate? findQqlCandidate(String id) {
      for (final candidate in qqlCandidates) {
        if (candidate.identity == id) return candidate;
      }
      return null;
    }

    CourseFlagCandidate? findWorldCandidate(String id) {
      for (final candidate in worldCandidates) {
        if (candidate.identity == 'world:$id') return candidate;
      }
      return null;
    }

    final qqlAutomatic = qqlFlag == null ? null : findQqlCandidate(qqlFlag.id);
    final worldAssociation = primaryWorldId == null
        ? null
        : findWorldCandidate(primaryWorldId);
    final automatic = qqlAutomatic ?? worldAssociation;
    final suggestedWorld = qqlAutomatic == null ? null : worldAssociation;

    return CourseFlagCatalog(
      sections: List.unmodifiable([
        CourseFlagCatalogSection(
          kind: CourseFlagCatalogSectionKind.qqlFlagPainter,
          title: 'QQL FlagPainter Flags',
          candidates: List.unmodifiable(qqlCandidates),
        ),
        CourseFlagCatalogSection(
          kind: CourseFlagCatalogSectionKind.worldFlags,
          title: 'WORLD Flags',
          candidates: List.unmodifiable(worldCandidates),
        ),
      ]),
      automaticCandidate: automatic,
      suggestedWorldFlag: suggestedWorld,
      automaticUnavailableMessage: automatic == null
          ? 'No automatic flag is available for this language.'
          : '',
      worldSuggestionUnavailableMessage: worldAssociation == null
          ? 'No associated WORLD Flag is available for this language.'
          : '',
    );
  }

  static String _worldSubtitle(WorldFlagEntity entity) {
    final code =
        entity.subdivisionCode ??
        entity.isoAlpha2 ??
        entity.isoAlpha3 ??
        entity.id;
    return 'WORLD Flag · $code';
  }
}
