import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:path_provider/path_provider.dart';

/// Writes uncaught Flutter/Dart errors to a persistent local text file.
///
/// The logger deliberately records only diagnostic information generated by
/// QuisquisLingo: timestamp, app version, platform, error and stack trace. It does
/// not collect course answers, profile names, or other user content.
class CrashLogService {
  CrashLogService._();

  static final CrashLogService instance = CrashLogService._();

  File? _file;
  File? _visibleLogFile;
  PackageInfo? _packageInfo;
  bool _initialised = false;

  Future<void> initialise() async {
    if (_initialised || kIsWeb) return;
    try {
      final directory = await getApplicationSupportDirectory();
      await directory.create(recursive: true);
      _file = File(
        '${directory.path}${Platform.pathSeparator}quisquislingo_crash.log',
      );
      // Debug builds also maintain an easy-to-find copy in the user's Documents
      // folder on Windows, so a tester can send the log without browsing AppData.
      // Alpha release builds use the same visible copy so standalone testers can
      // retrieve diagnostics without browsing the hidden Application Support path.
      if (Platform.isWindows) {
        final home = Platform.environment['USERPROFILE'];
        if (home != null && home.trim().isNotEmpty) {
          final visibleDir = Directory(
            '$home${Platform.pathSeparator}Documents${Platform.pathSeparator}QuisquisLingo Logs',
          );
          await visibleDir.create(recursive: true);
          _visibleLogFile = File(
            '${visibleDir.path}${Platform.pathSeparator}quisquislingo_crash.log',
          );
        }
      }
      _packageInfo = await PackageInfo.fromPlatform();
      _initialised = true;
      // Start every debug session with a system snapshot so even a native
      // process termination leaves useful environment details in the log.
      // The Alpha log now starts on every launch, including release builds.
      // FileMode.append creates the file again if a tester deleted it.
      await _recordSessionStart();
    } catch (error, stackTrace) {
      // Logging must never be able to crash the application itself.
      debugPrint('Crash logger initialisation failed: $error\n$stackTrace');
    }
  }

  Future<void> record(
    Object error,
    StackTrace stackTrace, {
    String source = 'uncaught',
  }) async {
    if (kIsWeb) return;
    if (!_initialised) await initialise();
    final file = _file;
    if (file == null) return;

    try {
      final info = _packageInfo;
      final buffer = StringBuffer()
        ..writeln('============================================================')
        ..writeln('QuisquisLingo crash report')
        ..writeln('Time: ${DateTime.now().toIso8601String()}')
        ..writeln('Source: $source')
        ..writeln(
          'Version: ${info?.version ?? 'unknown'}+${info?.buildNumber ?? 'unknown'}',
        )
        ..writeln('OS: ${Platform.operatingSystem} ${Platform.operatingSystemVersion}')
        ..writeln('Architecture: ${_architecture()}')
        ..writeln('Logical processors: ${Platform.numberOfProcessors}')
        ..writeln('Locale: ${Platform.localeName}')
        ..writeln('Dart runtime: ${Platform.version}')
        ..writeln('Error: $error')
        ..writeln('Stack trace:')
        ..writeln(stackTrace)
        ..writeln();
      await _appendToLogs(buffer.toString());
    } catch (loggingError, loggingStackTrace) {
      debugPrint('Writing crash log failed: $loggingError\n$loggingStackTrace');
    }
  }


  Future<void> _recordSessionStart() async {
    final info = _packageInfo;
    final buffer = StringBuffer()
      ..writeln('============================================================')
      ..writeln('QuisquisLingo session started')
      ..writeln('Time: ${DateTime.now().toIso8601String()}')
      ..writeln('Version: ${info?.version ?? 'unknown'}+${info?.buildNumber ?? 'unknown'}')
      ..writeln('OS: ${Platform.operatingSystem}')
      ..writeln('OS version: ${Platform.operatingSystemVersion}')
      ..writeln('Architecture: ${_architecture()}')
      ..writeln('Logical processors: ${Platform.numberOfProcessors}')
      ..writeln('Locale: ${Platform.localeName}')
      ..writeln('Dart runtime: ${Platform.version}')
      ..writeln('Build mode: ${_buildMode()}')
      ..writeln();
    await _appendToLogs(buffer.toString());
  }

  String _buildMode() {
    if (kReleaseMode) return 'release';
    if (kProfileMode) return 'profile';
    return 'debug';
  }

  String _architecture() {
    if (!Platform.isWindows) {
      return Platform.environment['HOSTTYPE'] ??
          Platform.environment['MACHTYPE'] ??
          'unknown';
    }
    return Platform.environment['PROCESSOR_ARCHITEW6432'] ??
        Platform.environment['PROCESSOR_ARCHITECTURE'] ??
        'unknown';
  }

  Future<void> _appendToLogs(String text) async {
    final targets = <File>{if (_file != null) _file!, if (_visibleLogFile != null) _visibleLogFile!};
    for (final target in targets) {
      try {
        await target.writeAsString(text, mode: FileMode.append, flush: true);
      } catch (error, stackTrace) {
        debugPrint('Writing crash log failed for ${target.path}: $error\n$stackTrace');
      }
    }
  }

  /// Lightweight breadcrumbs are enabled only in debug builds. They are
  /// flushed immediately so the last successful action survives a native crash.
  Future<void> recordDebugEvent(String message) async {
    if (!kDebugMode || kIsWeb) return;
    if (!_initialised) await initialise();
    final info = _packageInfo;
    final buffer = StringBuffer()
      ..writeln('------------------------------------------------------------')
      ..writeln('QuisquisLingo debug event')
      ..writeln('Time: ${DateTime.now().toIso8601String()}')
      ..writeln('Version: ${info?.version ?? 'unknown'}+${info?.buildNumber ?? 'unknown'}')
      ..writeln('Event: $message')
      ..writeln();
    await _appendToLogs(buffer.toString());
  }

  String? get visibleLogPath => _visibleLogFile?.path;

  /// Returns the easiest valid crash-log path for the current platform.
  /// Windows uses the visible Documents copy; other desktop platforms use the
  /// application-support log created by this service.
  String? get crashLogPath => _visibleLogFile?.path ?? _file?.path;

  void installFlutterHandler() {
    FlutterError.onError = (FlutterErrorDetails details) {
      FlutterError.presentError(details);
      unawaited(
        record(
          details.exception,
          details.stack ?? StackTrace.current,
          source: 'FlutterError.onError',
        ),
      );
    };

    PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
      unawaited(record(error, stack, source: 'PlatformDispatcher.onError'));
      return true;
    };
  }
}
