import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';

import 'app_metadata.dart';
import 'bounded_log_writer.dart';
import 'diagnostic_log_service.dart';
import 'storage/qql_storage.dart';

/// Writes uncaught Flutter/Dart errors to a persistent local text file.
///
/// The logger deliberately records only diagnostic information generated by
/// QuisquisLingo: timestamp, app version, platform, error and stack trace. It does
/// not collect course answers, profile names, or other user content.
class CrashLogService {
  static const _maximumLogBytes = 2 * 1024 * 1024;

  CrashLogService._();

  static final CrashLogService instance = CrashLogService._();

  File? _file;
  File? _markerFile;
  bool _cleanShutdownMarked = false;
  final DateTime _sessionStarted = DateTime.now();
  bool _initialised = false;
  // Once a persistent-storage attempt fails (for example the widget-test
  // harness, which has no real Documents directory), retrying on every
  // subsequent record*() call cannot succeed and only repeats the same
  // platform exception and warning. Remember the failure and stop retrying
  // for the remainder of this process/session.
  bool _initialisationFailed = false;

  Future<void> initialise() async {
    if (_initialised || _initialisationFailed || kIsWeb) return;
    try {
      final directory = await DiagnosticLogService.logsDirectory(create: true);
      if (directory == null) return;
      _file = File(
        '${directory.path}${Platform.pathSeparator}quisquislingo_crash.log',
      );
      // Only desktop close paths are hooked (see window_setup_io.dart), so
      // detection is limited there to avoid false alarms on mobile, where the
      // OS may end a session without any notification.
      if (Platform.isWindows || Platform.isLinux) {
        _markerFile = File(
          '${directory.path}${Platform.pathSeparator}quisquislingo_session.marker',
        );
      }
      _initialised = true;
      // Start every debug session with a system snapshot so even a native
      // process termination leaves useful environment details in the log.
      // The Beta log now starts on every launch, including release builds.
      // FileMode.append creates the file again if a tester deleted it.
      await _recordPreviousSessionOutcome();
      await _recordSessionStart();
      await _writeMarker('started');
    } catch (error, stackTrace) {
      // Logging must never be able to crash the application itself.
      _initialisationFailed = true;
      debugPrint('Crash logger initialisation failed: $error\n$stackTrace');
    }
  }

  Future<void> record(
    Object error,
    StackTrace stackTrace, {
    String source = 'uncaught',
  }) async {
    if (kIsWeb) return;
    if (!_initialised) await initialise();
    final file = _file;
    if (file == null) return;

    try {
      final buffer = StringBuffer()
        ..writeln(
          '============================================================',
        )
        ..writeln('QuisquisLingo crash report')
        ..writeln('Time: ${DateTime.now().toIso8601String()}')
        ..writeln('Source: $source')
        ..writeln('Version: ${AppMetadata.technicalVersion}')
        ..writeln(
          'OS: ${Platform.operatingSystem} ${Platform.operatingSystemVersion}',
        )
        ..writeln('Architecture: ${_architecture()}')
        ..writeln('Logical processors: ${Platform.numberOfProcessors}')
        ..writeln('Locale: ${Platform.localeName}')
        ..writeln('Dart runtime: ${Platform.version}')
        ..writeln('Error: $error')
        ..writeln('Stack trace:')
        ..writeln(stackTrace)
        ..writeln();
      await _appendToLogs(buffer.toString());
    } catch (loggingError, loggingStackTrace) {
      debugPrint('Writing crash log failed: $loggingError\n$loggingStackTrace');
    }
  }

  /// A marker file exists only while a session is running and is deleted on
  /// every clean shutdown. Finding one at startup therefore means the previous
  /// session was terminated without shutting down (native crash, force-kill,
  /// power loss), which no Dart error handler can observe.
  Future<void> _recordPreviousSessionOutcome() async {
    final marker = _markerFile;
    if (marker == null) return;
    try {
      if (!await marker.exists()) return;
      final previous = (await marker.readAsString()).trim();
      final buffer = StringBuffer()
        ..writeln(
          '============================================================',
        )
        ..writeln('QuisquisLingo abnormal termination detected')
        ..writeln('Time: ${DateTime.now().toIso8601String()}')
        ..writeln(
          'The previous session did not shut down cleanly. It may have '
          'crashed natively, been force-closed, or lost power.',
        )
        ..writeln('Previous session marker:')
        ..writeln(previous.isEmpty ? '(empty)' : previous)
        ..writeln();
      await _appendToLogs(buffer.toString());
    } catch (error, stackTrace) {
      debugPrint('Reading session marker failed: $error\n$stackTrace');
    }
  }

  Future<void> _writeMarker(String state) async {
    final marker = _markerFile;
    if (marker == null) return;
    try {
      await marker.writeAsString(
        'Started: ${_sessionStarted.toIso8601String()}\n'
        'Version: ${AppMetadata.technicalVersion}\n'
        'Build mode: ${_buildMode()}\n'
        'Last state: $state at ${DateTime.now().toIso8601String()}\n',
        flush: true,
      );
    } catch (error, stackTrace) {
      debugPrint('Writing session marker failed: $error\n$stackTrace');
    }
  }

  /// Records the latest lifecycle state so an abnormal-termination report
  /// says what the app was doing last.
  Future<void> recordLifecycleState(String state) async {
    if (_markerFile == null || _cleanShutdownMarked) return;
    await _writeMarker(state);
  }

  /// Call on every clean exit path. Synchronous so it can finish while the
  /// process is already shutting down.
  void markCleanShutdown() {
    if (_cleanShutdownMarked) return;
    _cleanShutdownMarked = true;
    // The log line is only history; the marker file alone drives detection, so
    // a failure here must not stop the marker from being removed.
    try {
      final file = _file;
      if (file != null) {
        file.writeAsStringSync(
          '------------------------------------------------------------\n'
          'QuisquisLingo session ended cleanly\n'
          'Time: ${DateTime.now().toIso8601String()}\n'
          'Started: ${_sessionStarted.toIso8601String()}\n\n',
          mode: FileMode.append,
          flush: true,
        );
      }
    } catch (error, stackTrace) {
      debugPrint('Writing clean shutdown entry failed: $error\n$stackTrace');
    }
    try {
      final marker = _markerFile;
      if (marker != null && marker.existsSync()) marker.deleteSync();
    } catch (error, stackTrace) {
      debugPrint('Removing session marker failed: $error\n$stackTrace');
    }
  }

  Future<void> _recordSessionStart() async {
    final buffer = StringBuffer()
      ..writeln('============================================================')
      ..writeln('QuisquisLingo session started')
      ..writeln('Time: ${DateTime.now().toIso8601String()}')
      ..writeln('Version: ${AppMetadata.technicalVersion}')
      ..writeln('OS: ${Platform.operatingSystem}')
      ..writeln('OS version: ${Platform.operatingSystemVersion}')
      ..writeln('Architecture: ${_architecture()}')
      ..writeln('Logical processors: ${Platform.numberOfProcessors}')
      ..writeln('Locale: ${Platform.localeName}')
      ..writeln('Dart runtime: ${Platform.version}')
      ..writeln('Build mode: ${_buildMode()}')
      ..writeln();
    await _appendToLogs(buffer.toString());
  }

  String _buildMode() {
    if (kReleaseMode) return 'release';
    if (kProfileMode) return 'profile';
    return 'debug';
  }

  String _architecture() {
    if (!Platform.isWindows) {
      return Platform.environment['HOSTTYPE'] ??
          Platform.environment['MACHTYPE'] ??
          'unknown';
    }
    return Platform.environment['PROCESSOR_ARCHITEW6432'] ??
        Platform.environment['PROCESSOR_ARCHITECTURE'] ??
        'unknown';
  }

  Future<void> _appendToLogs(String text) async {
    final targets = <File>{if (_file != null) _file!};
    for (final target in targets) {
      try {
        await BoundedLogWriter.appendFile(
          target,
          text,
          maximumBytes: _maximumLogBytes,
        );
      } catch (error, stackTrace) {
        debugPrint(
          'Writing crash log failed for ${target.path}: $error\n$stackTrace',
        );
      }
    }
  }

  /// Lightweight breadcrumbs are enabled only in debug builds. They are
  /// flushed immediately so the last successful action survives a native crash.
  Future<void> recordDebugEvent(String message) async {
    if (!kDebugMode || kIsWeb) return;
    if (!_initialised) await initialise();
    final buffer = StringBuffer()
      ..writeln('------------------------------------------------------------')
      ..writeln('QuisquisLingo debug event')
      ..writeln('Time: ${DateTime.now().toIso8601String()}')
      ..writeln('Version: ${AppMetadata.technicalVersion}')
      ..writeln('Event: $message')
      ..writeln();
    await _appendToLogs(buffer.toString());
  }

  /// Privacy-safe runtime audio lifecycle event. Callers pass only bounded
  /// technical tokens generated by AudioDiagnosticLifecycle.
  Future<void> recordAudioDiagnostic(String message) async {
    if (kIsWeb) return;
    if (!_initialised) await initialise();
    if (_file == null) return;
    final buffer = StringBuffer()
      ..writeln('------------------------------------------------------------')
      ..writeln('QuisquisLingo audio diagnostic')
      ..writeln('Time: ${DateTime.now().toIso8601String()}')
      ..writeln('Version: ${AppMetadata.technicalVersion}')
      ..writeln(message)
      ..writeln();
    await _appendToLogs(buffer.toString());
  }

  /// Tests only: makes the Crash Log unavailable for this process, as if its
  /// folder could not be made, without touching storage.
  @visibleForTesting
  void debugMarkUnavailable() {
    _initialisationFailed = true;
    _initialised = false;
    _file = null;
    _markerFile = null;
  }

  String? get visibleLogPath => _file?.path;

  /// Returns the easiest valid crash-log path for the current platform.
  String? get crashLogPath => _file?.path;

  static const exportBaseName = 'QQL_crash_log';
  static const exportFileName = 'QQL_crash_log.txt';

  /// Where Quick Export puts the Crash Log copy, for display.
  Future<String?> exportPath({QqlStorage? storage}) async {
    if (kIsWeb) return null;
    try {
      final folder = await (storage ?? QqlStorage()).exportFolder(
        QqlStorageRole.diagnosticLogExports,
      );
      return folder.locationOf(exportFileName);
    } catch (_) {
      return null;
    }
  }

  /// Quick Export: copies the live Crash Log into the Logs folder as
  /// [exportFileName], replacing the previous copy. The live file is only
  /// read. Null when there is no Crash Log; a failed write throws.
  Future<QuickExportResult?> exportCopy({QqlStorage? storage}) async {
    if (kIsWeb) return null;
    final file = _file;
    if (file == null || !await file.exists()) return null;
    final bytes = await file.readAsBytes();
    final folder = await (storage ?? QqlStorage()).exportFolder(
      QqlStorageRole.diagnosticLogExports,
    );
    return folder.write(
      baseName: exportBaseName,
      extension: 'txt',
      bytes: bytes,
      replace: true,
    );
  }

  void installFlutterHandler() {
    FlutterError.onError = (FlutterErrorDetails details) {
      FlutterError.presentError(details);
      unawaited(
        record(
          details.exception,
          details.stack ?? StackTrace.current,
          source: 'FlutterError.onError',
        ),
      );
    };

    PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
      unawaited(record(error, stack, source: 'PlatformDispatcher.onError'));
      return true;
    };
  }
}
