/// The French buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelFr = <String, String>{
  'check': 'Vérifier',
  'checkMatches': 'Vérifier les paires',
  'continue': 'Continuer',
  'testResults': 'Résultats du test · {percent}%',
  'testPassed': 'Réussi · {percent}%',
  'testBelowThreshold': 'Sous le seuil de réussite · {percent}%',
  'testQuestion': 'Question {n} : {status}',
  'testNextQuestion': 'Question suivante',
  'testSeeResults': 'Voir les résultats',
  'correct': 'Correct',
  'incorrect': 'Incorrect',
  'hint': 'Indice : {hint}',
  'yourAnswer': 'Ta réponse',
  'missingWord': 'Mot manquant',
  'missingLetters': 'Lettres manquantes',
  'correctAnswer': 'Bonne réponse : {answer}',
  'correctAnswerLabel': 'Bonne réponse :',
  'correctTranslations': 'Traductions correctes :',
  'otherCorrectTranslations': 'Autres traductions correctes :',
  'somePossibleTranslations': 'Quelques traductions possibles :',
  'acceptedDifference': 'Différence acceptée : {list}',
  'acceptedDifferences': 'Différences acceptées : {list}',
  'seeCourseAnswer': 'Vois la réponse du cours.',
  'reviewTheFlashcard': 'Revois la carte.',
  'playAudio': 'Écouter l’audio',
  'playAudioAgain': 'Réécouter',
  'playSound': 'Écouter le son',
  'play': 'Écouter',
  'audioUnavailable': 'Audio indisponible',
  'audioOffNote':
      'L’audio est désactivé ou indisponible. L’exercice fonctionne quand même.',
  'audioNotOnDevice': 'Audio indisponible sur cet appareil.',
  'listenToAnswer': 'Écoute la réponse',
  'listenFirst': 'Écoute d’abord…',
  'listen': 'Écoute…',
  'usage': 'Emploi :',
  'pronounceWord': 'Prononcer le mot ou la phrase',
  'pronounceUsage': 'Prononcer la phrase d’exemple',
  'reviewAgain': 'Revoir plus tard',
  'gotIt': 'Compris',
  'cardAgainLater': 'Cette carte reviendra plus tard dans cette manche.',
  'cardReviewed': 'Carte revue.',
  'linkNotOpened': 'Impossible d’ouvrir le lien.',
  'empty': 'Vide',
  'nothingHereYet': 'Rien pour l’instant',
  'slotNumber': 'Case {n}',
  'gapNumber': 'Blanc {n}',
  'groupNumber': 'Groupe {n}',
  'beforeYouStart': 'Avant de commencer',
  'openGuidebook': 'Ouvrir le guide',
  'continueToRound': 'Passer à la manche',
  'lessonLine': '{language} · Leçon {n} · {title}',
  'roundInReview': '{round} · Révision',
  'reviewOfRound': 'Révision · {round}',
  'reviewingMissed': 'Révision des exercices ratés',
  'reviewMistakesTitle': 'Revois tes erreurs',
  'reviewMistakesBody': 'Réessayons les exercices que tu as ratés.',
  'reviewMistakes': 'Revoir les erreurs',
  'finish.round': 'Terminer la manche',
  'finish.story': 'Terminer l’histoire',
  'finish.sequence': 'Terminer la séquence',
  'finishing.round': 'Fin de la manche…',
  'finishing.story': 'Fin de l’histoire…',
  'finishing.sequence': 'Fin de la séquence…',
  'leave.round': 'Quitter la manche',
  'leave.story': 'Quitter l’histoire',
  'leave.sequence': 'Quitter la séquence',
  'completed.round': 'Manche terminée',
  'completed.story': 'Histoire terminée',
  'completed.sequence': 'Séquence terminée',
  'nothingToScore.round': 'Rien à noter dans cette manche.',
  'nothingToScore.story': 'Rien à noter dans cette histoire.',
  'nothingToScore.sequence': 'Rien à noter dans cette séquence.',
  'steps.round': 'Manche · {n} étapes',
  'steps.story': 'Histoire · {n} étapes',
  'steps.sequence': 'Séquence · {n} étapes',
  'summary.correctAnswers': 'Bonnes réponses : {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Bonus de difficulté : +{xp} XP',
  'summary.onTimeBonus': 'Bonus de fin à temps : +{xp} XP',
  'timed.timeLeft': 'Temps restant : {time}',
  'timed.timeUp': 'Temps écoulé',
  'timed.incomplete':
      'Ce Round est incomplet. Les activités sans réponse le restent.',
  'timed.correctXpKept': 'XP conservés pour les bonnes réponses : {xp}',
  'timed.retrySaving': 'Réessayer d’enregistrer les XP',
  'timed.retry': 'Réessayer le Round',
  'summary.perfectBonus': 'Bonus parfait : +{xp} XP',
  'summary.firstLaurel': 'Premier laurier : +{xp} XP',
  'summary.lessonCompleted': 'Leçon terminée : +{xp} XP',
  'summary.total': 'Total : {xp} XP',
  'weeklyGoalReached': 'Objectif hebdomadaire atteint !',
  'duel.title': 'Duel de langues',
  'duel.finalTitle': 'Duel final',
  'duel.question': 'Question {n}/{total} · 4 vies',
  'duel.listenChooseMeaning': 'Écoute et choisis le sens.',
  'duel.finishing': 'Fin du duel…',
  'duel.finish': 'Terminer le duel',
  'duel.finalCompleted': 'Duel final terminé !',
  'duel.won': 'Duel gagné',
  'duel.lost': 'Duel perdu',
  'duel.wonBody':
      'Duel gagné : +{xp} XP\n\nTu as prouvé tes connaissances. La leçon suivante peut maintenant se débloquer.',
  'duel.lostLives': 'Duel perdu. Tu as perdu tes quatre vies.',
  'duel.endedEarly': 'Le duel s’est terminé avant la fin des 25 questions.',
  'duel.backToCourse': 'Retour au cours',
  'review.title': 'Révision',
  'review.beforeRound': 'Avant la manche',
  'review.afterRound': 'Après la manche',
  'review.lesson': 'Leçon {n} : {title}',
  'review.round': 'Manche {n}',
  'review.word': 'Mot {i} sur {n}',
  'review.showAnswer': 'Afficher la réponse',
  'review.nowIKnow': 'Maintenant je le sais',
  'review.iKnowIt': 'Je le sais',
  'review.stillDontKnow': 'Je ne le sais toujours pas',
  'review.showAgain': 'Montre-le-moi encore',
  'review.completed': 'Révision terminée !',
  'review.ready': 'Prêt pour la révision',
  'review.noMoreRounds': 'Plus aucune manche dans cette session de révision.',
  'review.wordsToReview.one':
      '{n} mot à réviser lors de la prochaine révision.',
  'review.wordsToReview.other':
      '{n} mots à réviser lors de la prochaine révision.',
  'review.next': 'Révision suivante',
  'review.backToCourse': 'Retour au cours',
  'review.noRounds': 'Ce cours n’a aucune manche à réviser.',
};
