/// The German buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelDe = <String, String>{
  'check': 'Prüfen',
  'checkMatches': 'Paare prüfen',
  'continue': 'Weiter',
  'testResults': 'Testergebnisse · {percent}%',
  'testPassed': 'Bestanden · {percent}%',
  'testBelowThreshold': 'Unter der Bestehensgrenze · {percent}%',
  'testQuestion': 'Frage {n}: {status}',
  'testNextQuestion': 'Nächste Frage',
  'testSeeResults': 'Ergebnisse ansehen',
  'correct': 'Richtig',
  'incorrect': 'Falsch',
  'hint': 'Tipp: {hint}',
  'yourAnswer': 'Deine Antwort',
  'missingWord': 'Fehlendes Wort',
  'missingLetters': 'Fehlende Buchstaben',
  'correctAnswer': 'Richtige Antwort: {answer}',
  'correctAnswerLabel': 'Richtige Antwort:',
  'correctTranslations': 'Richtige Übersetzungen:',
  'otherCorrectTranslations': 'Weitere richtige Übersetzungen:',
  'somePossibleTranslations': 'Einige mögliche Übersetzungen:',
  'acceptedDifference': 'Akzeptierter Unterschied: {list}',
  'acceptedDifferences': 'Akzeptierte Unterschiede: {list}',
  'seeCourseAnswer': 'Siehe die Antwort im Kurs.',
  'reviewTheFlashcard': 'Sieh dir die Karte noch einmal an.',
  'playAudio': 'Audio abspielen',
  'playAudioAgain': 'Erneut abspielen',
  'playSound': 'Ton abspielen',
  'play': 'Abspielen',
  'audioUnavailable': 'Audio nicht verfügbar',
  'audioOffNote':
      'Audio ist ausgeschaltet oder nicht verfügbar. Die Übung funktioniert trotzdem.',
  'audioNotOnDevice': 'Audio auf diesem Gerät nicht verfügbar.',
  'listenToAnswer': 'Hör dir die Antwort an',
  'listenFirst': 'Erst zuhören…',
  'listen': 'Hör zu…',
  'usage': 'Verwendung:',
  'pronounceWord': 'Wort oder Satz aussprechen',
  'pronounceUsage': 'Beispielsatz aussprechen',
  'reviewAgain': 'Nochmal wiederholen',
  'gotIt': 'Verstanden',
  'cardAgainLater': 'Diese Karte kommt später in dieser Runde noch einmal.',
  'cardReviewed': 'Karte wiederholt.',
  'turnOver': 'Umdrehen',
  'tapToTurn': 'Tippe auf die Karte, um sie umzudrehen',
  'linkNotOpened': 'Der Link konnte nicht geöffnet werden.',
  'linkAskTitle': 'Diesen Link öffnen?',
  'linkAskBody':
      'Diese Seite verweist auf {site}. Der Link öffnet sich in deinem Browser, außerhalb von QuisquisLingo:',
  'linkAskOpen': 'Link öffnen',
  'linkAskCancel': 'Abbrechen',
  'empty': 'Leer',
  'nothingHereYet': 'Noch nichts hier',
  'slotNumber': 'Feld {n}',
  'gapNumber': 'Lücke {n}',
  'groupNumber': 'Gruppe {n}',
  'beforeYouStart': 'Bevor du anfängst',
  'openGuidebook': 'Leitfaden öffnen',
  'continueToRound': 'Weiter zur Runde',
  'lessonLine': '{language} · Lektion {n} · {title}',
  'roundInReview': '{round} · Wiederholung',
  'reviewOfRound': 'Wiederholung · {round}',
  'reviewingMissed': 'Wiederholung der falsch beantworteten Übungen',
  'reviewMistakesTitle': 'Wiederhole deine Fehler',
  'reviewMistakesBody':
      'Versuchen wir die Übungen noch einmal, die du falsch hattest.',
  'reviewMistakes': 'Fehler wiederholen',
  'finish.round': 'Runde beenden',
  'finish.story': 'Geschichte beenden',
  'finish.sequence': 'Sequenz beenden',
  'finishing.round': 'Runde wird beendet…',
  'finishing.story': 'Geschichte wird beendet…',
  'finishing.sequence': 'Sequenz wird beendet…',
  'leave.round': 'Runde verlassen',
  'leave.story': 'Geschichte verlassen',
  'leave.sequence': 'Sequenz verlassen',
  'completed.round': 'Runde abgeschlossen',
  'completed.story': 'Geschichte abgeschlossen',
  'completed.sequence': 'Sequenz abgeschlossen',
  'nothingToScore.round': 'In dieser Runde gibt es nichts zu bewerten.',
  'nothingToScore.story': 'In dieser Geschichte gibt es nichts zu bewerten.',
  'nothingToScore.sequence': 'In dieser Sequenz gibt es nichts zu bewerten.',
  'steps.round': 'Runde · {n} Schritte',
  'steps.story': 'Geschichte · {n} Schritte',
  'steps.sequence': 'Sequenz · {n} Schritte',
  'summary.correctAnswers': 'Richtige Antworten: {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Schwierigkeitsbonus: +{xp} XP',
  'summary.onTimeBonus': 'Pünktlichkeitsbonus: +{xp} XP',
  'timed.timeLeft': 'Verbleibende Zeit: {time}',
  'timed.timeUp': 'Die Zeit ist um',
  'timed.incomplete':
      'Diese Runde ist unvollständig. Unbeantwortete Aufgaben bleiben offen.',
  'timed.correctXpKept': 'XP für richtige Antworten behalten: {xp}',
  'timed.retrySaving': 'XP erneut speichern',
  'timed.retry': 'Runde erneut versuchen',
  'summary.perfectBonus': 'Perfekt-Bonus: +{xp} XP',
  'summary.firstLaurel': 'Erster Lorbeer: +{xp} XP',
  'summary.lessonCompleted': 'Lektion abgeschlossen: +{xp} XP',
  'summary.total': 'Gesamt: {xp} XP',
  'weeklyGoalReached': 'Wochenziel erreicht!',
  'duel.title': 'Sprachduell',
  'duel.finalTitle': 'Finales Duell',
  'duel.question': 'Frage {n}/{total} · 4 Leben',
  'duel.listenChooseMeaning': 'Hör zu und wähle die Bedeutung.',
  'duel.finishing': 'Duell wird beendet…',
  'duel.finish': 'Duell beenden',
  'duel.finalCompleted': 'Finales Duell geschafft!',
  'duel.won': 'Duell gewonnen',
  'duel.lost': 'Duell verloren',
  'duel.wonBody':
      'Duell gewonnen: +{xp} XP\n\nDu hast dein Wissen bewiesen. Die nächste Lektion kann jetzt freigeschaltet werden.',
  'duel.lostLives': 'Duell verloren. Du hast alle vier Leben verloren.',
  'duel.endedEarly':
      'Das Duell endete, bevor alle 25 Fragen beantwortet waren.',
  'duel.backToCourse': 'Zurück zum Kurs',
  'review.title': 'Wiederholung',
  'review.beforeRound': 'Vor der Runde',
  'review.afterRound': 'Nach der Runde',
  'review.lesson': 'Lektion {n}: {title}',
  'review.round': 'Runde {n}',
  'review.word': 'Wort {i} von {n}',
  'review.showAnswer': 'Antwort zeigen',
  'review.nowIKnow': 'Jetzt kann ich es',
  'review.iKnowIt': 'Ich kann es',
  'review.stillDontKnow': 'Ich kann es noch nicht',
  'review.showAgain': 'Zeig es mir noch einmal',
  'review.completed': 'Wiederholung abgeschlossen!',
  'review.ready': 'Bereit zur Wiederholung',
  'review.noMoreRounds':
      'In dieser Wiederholung gibt es keine weiteren Runden.',
  'review.wordsToReview.one': '{n} Wort für die nächste Wiederholung.',
  'review.wordsToReview.other': '{n} Wörter für die nächste Wiederholung.',
  'review.next': 'Nächste Wiederholung',
  'review.backToCourse': 'Zurück zum Kurs',
  'review.noRounds': 'In diesem Kurs gibt es keine Runden zum Wiederholen.',
  // Build 265: Word Lookup.
  'wordLookup.note':
      'Eine mögliche Übersetzung aus dem GuideBook dieses Kurses.',
  'wordLookup.notes':
      'Einige mögliche Übersetzungen aus dem GuideBook dieses Kurses.',
  'wordLookup.notice':
      'Tippe auf ein gepunktet unterstrichenes Wort, um eine Übersetzung aus dem GuideBook des Kurses zu sehen. Nur manche Übungsarten haben sie. Sie ist ein Hinweis, eine mögliche Übersetzung, und stimmt nicht immer mit der Lösung der Übung überein.',
  'wordLookup.action': 'Vokabeln in diesem Text',
};
