/// The English buttons and messages of the learner panel (Build 260
/// Revision 1).
const learnerPanelEn = <String, String>{
  'check': 'Check',
  'checkMatches': 'Check matches',
  'continue': 'Continue',
  'testResults': 'Test results · {percent}%',
  'testPassed': 'Passed · {percent}%',
  'testBelowThreshold': 'Below passing threshold · {percent}%',
  'testQuestion': 'Question {n}: {status}',
  'testNextQuestion': 'Next question',
  'testSeeResults': 'See results',
  'correct': 'Correct',
  'incorrect': 'Incorrect',
  'hint': 'Hint: {hint}',
  'yourAnswer': 'Your answer',
  'missingWord': 'Missing word',
  'missingLetters': 'Missing letters',
  'correctAnswer': 'Correct answer: {answer}',
  'correctAnswerLabel': 'Correct answer:',
  'correctTranslations': 'Correct translations:',
  'otherCorrectTranslations': 'Other correct translations:',
  'somePossibleTranslations': 'Some possible translations:',
  'acceptedDifference': 'Accepted difference: {list}',
  'acceptedDifferences': 'Accepted differences: {list}',
  'seeCourseAnswer': 'See the course answer.',
  'reviewTheFlashcard': 'Review the flashcard.',
  'playAudio': 'Play audio',
  'playAudioAgain': 'Play audio again',
  'playSound': 'Play sound',
  'play': 'Play',
  'audioUnavailable': 'Audio unavailable',
  'audioOffNote':
      'Audio is turned off or unavailable. The exercise still works.',
  'audioNotOnDevice': 'Audio not available on this device.',
  'listenToAnswer': 'Listen to the answer',
  'listenFirst': 'Listen first…',
  'listen': 'Listen…',
  'usage': 'Usage:',
  'pronounceWord': 'Pronounce word or phrase',
  'pronounceUsage': 'Pronounce usage sentence',
  'reviewAgain': 'Review again',
  'gotIt': 'Got it',
  'cardAgainLater': 'This card will be shown again later in this round.',
  'cardReviewed': 'Card reviewed.',
  'linkNotOpened': 'The link could not be opened.',
  'empty': 'Empty',
  'nothingHereYet': 'Nothing here yet',
  'slotNumber': 'Slot {n}',
  'gapNumber': 'Gap {n}',
  'groupNumber': 'Group {n}',
  'beforeYouStart': 'Before you start',
  'openGuidebook': 'Open Guidebook',
  'continueToRound': 'Continue to Round',
  'lessonLine': '{language} · Lesson {n} · {title}',
  'roundInReview': '{round} · Review',
  'reviewOfRound': 'Review · {round}',
  'reviewingMissed': 'Reviewing exercises you missed',
  'reviewMistakesTitle': 'Review your mistakes',
  'reviewMistakesBody': 'Let\'s try again the exercises you got wrong.',
  'reviewMistakes': 'Review mistakes',
  'finish.round': 'Finish round',
  'finish.story': 'Finish story',
  'finish.sequence': 'Finish sequence',
  'finishing.round': 'Finishing round…',
  'finishing.story': 'Finishing story…',
  'finishing.sequence': 'Finishing sequence…',
  'leave.round': 'Leave round',
  'leave.story': 'Leave story',
  'leave.sequence': 'Leave sequence',
  'completed.round': 'Round completed',
  'completed.story': 'Story completed',
  'completed.sequence': 'Sequence completed',
  'nothingToScore.round': 'Nothing to score in this Round.',
  'nothingToScore.story': 'Nothing to score in this Story.',
  'nothingToScore.sequence': 'Nothing to score in this Sequence.',
  'steps.round': 'Round · {n} steps',
  'steps.story': 'Story · {n} steps',
  'steps.sequence': 'Sequence · {n} steps',
  'summary.correctAnswers': 'Correct answers: {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Difficulty bonus: +{xp} XP',
  'summary.onTimeBonus': 'On Time bonus: +{xp} XP',
  'timed.timeLeft': 'Time left: {time}',
  'timed.timeUp': 'Time is up',
  'timed.incomplete':
      'This Round is incomplete. Unanswered activities stay unanswered.',
  'timed.correctXpKept': 'Correct-answer XP kept: {xp}',
  'timed.retrySaving': 'Retry saving XP',
  'timed.retry': 'Retry Round',
  'summary.perfectBonus': 'Perfect bonus: +{xp} XP',
  'summary.firstLaurel': 'First Laurel: +{xp} XP',
  'summary.lessonCompleted': 'Lesson completed: +{xp} XP',
  'summary.total': 'Total: {xp} XP',
  'weeklyGoalReached': 'Weekly goal reached!',
  'duel.title': 'Language Duel',
  'duel.finalTitle': 'Final Duel',
  'duel.question': 'Question {n}/{total} · 4 lives',
  'duel.listenChooseMeaning': 'Listen and choose the meaning.',
  'duel.finishing': 'Finishing duel…',
  'duel.finish': 'Finish duel',
  'duel.finalCompleted': 'Final Duel completed!',
  'duel.won': 'Duel won',
  'duel.lost': 'Duel lost',
  'duel.wonBody':
      'Duel won: +{xp} XP\n\nYou proved your knowledge. The next Lesson can now unlock.',
  'duel.lostLives': 'Duel lost. You have lost all four lives.',
  'duel.endedEarly': 'The duel ended before all 25 questions were completed.',
  'duel.backToCourse': 'Back to course',
  'review.title': 'Review',
  'review.beforeRound': 'Before the Round',
  'review.afterRound': 'After the Round',
  'review.lesson': 'Lesson {n}: {title}',
  'review.round': 'Round {n}',
  'review.word': 'Word {i} of {n}',
  'review.showAnswer': 'Show answer',
  'review.nowIKnow': 'Now I know it',
  'review.iKnowIt': 'I know it',
  'review.stillDontKnow': 'I still don\'t know it',
  'review.showAgain': 'Show it to me again',
  'review.completed': 'Review completed!',
  'review.ready': 'Ready for Review',
  'review.noMoreRounds': 'No more Rounds are available in this Review session.',
  'review.wordsToReview.one': '{n} word to review in the next Review.',
  'review.wordsToReview.other': '{n} words to review in the next Review.',
  'review.next': 'Next Review',
  'review.backToCourse': 'Back to Course',
  'review.noRounds': 'There are no Rounds available for Review in this course.',
  // Build 265: Word Lookup.
  'wordLookup.note': 'One possible translation from this Course\'s GuideBook.',
  'wordLookup.notes':
      'Some possible translations from this Course\'s GuideBook.',
  'wordLookup.notice':
      'Tap a word with a dotted underline to see a translation from this Course\'s GuideBook. Only some exercise types have them. It is a hint, one possible translation: it does not always match the answer to the exercise.',
  'wordLookup.action': 'Vocabulary in this text',
};
