/// The Italian buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelIt = <String, String>{
  'check': 'Controlla',
  'checkMatches': 'Controlla le coppie',
  'continue': 'Continua',
  'correct': 'Corretto',
  'incorrect': 'Sbagliato',
  'hint': 'Suggerimento: {hint}',
  'yourAnswer': 'La tua risposta',
  'missingWord': 'Parola mancante',
  'missingLetters': 'Lettere mancanti',
  'correctAnswer': 'Risposta corretta: {answer}',
  'correctAnswerLabel': 'Risposta corretta:',
  'correctTranslations': 'Traduzioni corrette:',
  'otherCorrectTranslations': 'Altre traduzioni corrette:',
  'somePossibleTranslations': 'Alcune traduzioni possibili:',
  'acceptedDifference': 'Differenza accettata: {list}',
  'acceptedDifferences': 'Differenze accettate: {list}',
  'seeCourseAnswer': 'Vedi la risposta del corso.',
  'reviewTheFlashcard': 'Ripassa la scheda.',
  'playAudio': 'Riproduci l’audio',
  'playAudioAgain': 'Riascolta',
  'playSound': 'Riproduci il suono',
  'play': 'Riproduci',
  'audioUnavailable': 'Audio non disponibile',
  'audioOffNote':
      'L’audio è spento o non disponibile. L’esercizio funziona comunque.',
  'audioNotOnDevice': 'Audio non disponibile su questo dispositivo.',
  'listenToAnswer': 'Ascolta la risposta',
  'listenFirst': 'Prima ascolta…',
  'listen': 'Ascolta…',
  'usage': 'Uso:',
  'pronounceWord': 'Pronuncia la parola o la frase',
  'pronounceUsage': 'Pronuncia la frase d’esempio',
  'reviewAgain': 'Ripeti più tardi',
  'gotIt': 'Ho capito',
  'cardAgainLater': 'Questa scheda tornerà più avanti in questo round.',
  'cardReviewed': 'Scheda ripassata.',
  'linkNotOpened': 'Impossibile aprire il link.',
  'empty': 'Vuoto',
  'nothingHereYet': 'Ancora niente',
  'slotNumber': 'Casella {n}',
  'gapNumber': 'Spazio {n}',
  'groupNumber': 'Gruppo {n}',
  'beforeYouStart': 'Prima di iniziare',
  'openGuidebook': 'Apri la guida',
  'continueToRound': 'Vai al round',
  'lessonLine': '{language} · Lezione {n} · {title}',
  'roundInReview': '{round} · Ripasso',
  'reviewOfRound': 'Ripasso · {round}',
  'reviewingMissed': 'Ripasso degli esercizi sbagliati',
  'reviewMistakesTitle': 'Rivedi i tuoi errori',
  'reviewMistakesBody': 'Riproviamo gli esercizi che hai sbagliato.',
  'reviewMistakes': 'Rivedi gli errori',
  'finish.round': 'Termina il round',
  'finish.story': 'Termina la storia',
  'finish.sequence': 'Termina la sequenza',
  'finishing.round': 'Chiusura del round…',
  'finishing.story': 'Chiusura della storia…',
  'finishing.sequence': 'Chiusura della sequenza…',
  'leave.round': 'Esci dal round',
  'leave.story': 'Esci dalla storia',
  'leave.sequence': 'Esci dalla sequenza',
  'completed.round': 'Round completato',
  'completed.story': 'Storia completata',
  'completed.sequence': 'Sequenza completata',
  'nothingToScore.round': 'Niente da valutare in questo round.',
  'nothingToScore.story': 'Niente da valutare in questa storia.',
  'nothingToScore.sequence': 'Niente da valutare in questa sequenza.',
  'steps.round': 'Round · {n} passi',
  'steps.story': 'Storia · {n} passi',
  'steps.sequence': 'Sequenza · {n} passi',
  'summary.correctAnswers': 'Risposte corrette: {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Bonus difficoltà: +{xp} XP',
  'summary.perfectBonus': 'Bonus perfetto: +{xp} XP',
  'summary.firstLaurel': 'Primo alloro: +{xp} XP',
  'summary.lessonCompleted': 'Lezione completata: +{xp} XP',
  'summary.total': 'Totale: {xp} XP',
  'weeklyGoalReached': 'Obiettivo settimanale raggiunto!',
  'duel.title': 'Duello linguistico',
  'duel.finalTitle': 'Duello finale',
  'duel.question': 'Domanda {n}/{total} · 4 vite',
  'duel.listenChooseMeaning': 'Ascolta e scegli il significato.',
  'duel.finishing': 'Chiusura del duello…',
  'duel.finish': 'Termina il duello',
  'duel.finalCompleted': 'Duello finale completato!',
  'duel.won': 'Duello vinto',
  'duel.lost': 'Duello perso',
  'duel.wonBody':
      'Duello vinto: +{xp} XP\n\nHai dimostrato quello che sai. Ora la lezione successiva può sbloccarsi.',
  'duel.lostLives': 'Duello perso. Hai perso tutte e quattro le vite.',
  'duel.endedEarly': 'Il duello è finito prima di completare le 25 domande.',
  'duel.backToCourse': 'Torna al corso',
  'review.title': 'Ripasso',
  'review.beforeRound': 'Prima del round',
  'review.afterRound': 'Dopo il round',
  'review.lesson': 'Lezione {n}: {title}',
  'review.round': 'Round {n}',
  'review.word': 'Parola {i} di {n}',
  'review.showAnswer': 'Mostra la risposta',
  'review.nowIKnow': 'Ora la so',
  'review.iKnowIt': 'La so',
  'review.stillDontKnow': 'Ancora non la so',
  'review.showAgain': 'Fammela rivedere',
  'review.completed': 'Ripasso completato!',
  'review.ready': 'Pronto per il ripasso',
  'review.noMoreRounds':
      'Non ci sono altri round in questa sessione di ripasso.',
  'review.wordsToReview.one': '{n} parola da ripassare nel prossimo ripasso.',
  'review.wordsToReview.other': '{n} parole da ripassare nel prossimo ripasso.',
  'review.next': 'Prossimo ripasso',
  'review.backToCourse': 'Torna al corso',
  'review.noRounds': 'In questo corso non ci sono round da ripassare.',
};
