/// The Portuguese buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelPt = <String, String>{
  'check': 'Verificar',
  'checkMatches': 'Verificar pares',
  'continue': 'Continuar',
  'testResults': 'Resultados do teste · {percent}%',
  'testPassed': 'Aprovado · {percent}%',
  'testBelowThreshold': 'Abaixo da nota mínima · {percent}%',
  'testQuestion': 'Pergunta {n}: {status}',
  'testNextQuestion': 'Próxima pergunta',
  'testSeeResults': 'Ver resultados',
  'correct': 'Correto',
  'incorrect': 'Incorreto',
  'hint': 'Dica: {hint}',
  'yourAnswer': 'A sua resposta',
  'missingWord': 'Palavra em falta',
  'missingLetters': 'Letras em falta',
  'correctAnswer': 'Resposta correta: {answer}',
  'correctAnswerLabel': 'Resposta correta:',
  'correctTranslations': 'Traduções corretas:',
  'otherCorrectTranslations': 'Outras traduções corretas:',
  'somePossibleTranslations': 'Algumas traduções possíveis:',
  'acceptedDifference': 'Diferença admitida: {list}',
  'acceptedDifferences': 'Diferenças admitidas: {list}',
  'seeCourseAnswer': 'Veja a resposta do curso.',
  'reviewTheFlashcard': 'Reveja o cartão.',
  'playAudio': 'Reproduzir áudio',
  'playAudioAgain': 'Ouvir de novo',
  'playSound': 'Reproduzir som',
  'play': 'Reproduzir',
  'audioUnavailable': 'Áudio indisponível',
  'audioOffNote':
      'O áudio está desligado ou indisponível. O exercício funciona na mesma.',
  'audioNotOnDevice': 'Áudio indisponível neste dispositivo.',
  'listenToAnswer': 'Ouça a resposta',
  'listenFirst': 'Ouça primeiro…',
  'listen': 'Ouça…',
  'usage': 'Uso:',
  'pronounceWord': 'Pronunciar a palavra ou frase',
  'pronounceUsage': 'Pronunciar a frase de exemplo',
  'reviewAgain': 'Rever outra vez',
  'gotIt': 'Entendido',
  'cardAgainLater': 'Este cartão voltará mais tarde nesta ronda.',
  'cardReviewed': 'Cartão revisto.',
  'turnOver': 'Virar',
  'tapToTurn': 'Toque no cartão para o virar',
  'linkNotOpened': 'Não foi possível abrir o link.',
  'linkAskTitle': 'Abrir este link?',
  'linkAskBody':
      'Esta página leva a {site}. Abre-se no navegador, fora do QuisquisLingo:',
  'linkAskOpen': 'Abrir link',
  'linkAskCancel': 'Cancelar',
  'empty': 'Vazio',
  'nothingHereYet': 'Ainda nada aqui',
  'slotNumber': 'Espaço {n}',
  'gapNumber': 'Lacuna {n}',
  'groupNumber': 'Grupo {n}',
  'beforeYouStart': 'Antes de começar',
  'openGuidebook': 'Abrir o guia',
  'continueToRound': 'Ir para a ronda',
  'lessonLine': '{language} · Lição {n} · {title}',
  'roundInReview': '{round} · Revisão',
  'reviewOfRound': 'Revisão · {round}',
  'reviewingMissed': 'Revisão dos exercícios errados',
  'reviewMistakesTitle': 'Reveja os seus erros',
  'reviewMistakesBody': 'Vamos tentar de novo os exercícios errados.',
  'reviewMistakes': 'Rever os erros',
  'finish.round': 'Terminar a ronda',
  'finish.story': 'Terminar a história',
  'finish.sequence': 'Terminar a sequência',
  'finishing.round': 'A terminar a ronda…',
  'finishing.story': 'A terminar a história…',
  'finishing.sequence': 'A terminar a sequência…',
  'leave.round': 'Sair da ronda',
  'leave.story': 'Sair da história',
  'leave.sequence': 'Sair da sequência',
  'completed.round': 'Ronda concluída',
  'completed.story': 'História concluída',
  'completed.sequence': 'Sequência concluída',
  'nothingToScore.round': 'Nada a pontuar nesta ronda.',
  'nothingToScore.story': 'Nada a pontuar nesta história.',
  'nothingToScore.sequence': 'Nada a pontuar nesta sequência.',
  'steps.round': 'Ronda · {n} passos',
  'steps.story': 'História · {n} passos',
  'steps.sequence': 'Sequência · {n} passos',
  'summary.correctAnswers': 'Respostas corretas: {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Bónus de dificuldade: +{xp} XP',
  'summary.onTimeBonus': 'Bónus por terminar a tempo: +{xp} XP',
  'timed.timeLeft': 'Tempo restante: {time}',
  'timed.timeUp': 'O tempo terminou',
  'timed.incomplete':
      'Esta Ronda está incompleta. As atividades sem resposta continuam por responder.',
  'timed.correctXpKept': 'XP das respostas certas mantidos: {xp}',
  'timed.retrySaving': 'Tentar guardar os XP novamente',
  'timed.retry': 'Tentar a Ronda novamente',
  'summary.perfectBonus': 'Bónus perfeito: +{xp} XP',
  'summary.firstLaurel': 'Primeiro louro: +{xp} XP',
  'summary.lessonCompleted': 'Lição concluída: +{xp} XP',
  'summary.total': 'Total: {xp} XP',
  'weeklyGoalReached': 'Objetivo semanal alcançado!',
  'duel.title': 'Duelo de línguas',
  'duel.finalTitle': 'Duelo final',
  'duel.question': 'Pergunta {n}/{total} · 4 vidas',
  'duel.listenChooseMeaning': 'Ouça e escolha o significado.',
  'duel.finishing': 'A terminar o duelo…',
  'duel.finish': 'Terminar o duelo',
  'duel.finalCompleted': 'Duelo final concluído!',
  'duel.won': 'Duelo ganho',
  'duel.lost': 'Duelo perdido',
  'duel.wonBody':
      'Duelo ganho: +{xp} XP\n\nMostrou o que sabe. A lição seguinte já pode ser desbloqueada.',
  'duel.lostLives': 'Duelo perdido. Perdeu as quatro vidas.',
  'duel.endedEarly': 'O duelo terminou antes de completar as 25 perguntas.',
  'duel.backToCourse': 'Voltar ao curso',
  'review.title': 'Revisão',
  'review.beforeRound': 'Antes da ronda',
  'review.afterRound': 'Depois da ronda',
  'review.lesson': 'Lição {n}: {title}',
  'review.round': 'Ronda {n}',
  'review.word': 'Palavra {i} de {n}',
  'review.showAnswer': 'Mostrar resposta',
  'review.nowIKnow': 'Agora já sei',
  'review.iKnowIt': 'Já sei',
  'review.stillDontKnow': 'Ainda não sei',
  'review.showAgain': 'Mostrar outra vez',
  'review.completed': 'Revisão concluída!',
  'review.ready': 'Pronto para rever',
  'review.noMoreRounds': 'Não há mais rondas nesta sessão de revisão.',
  'review.wordsToReview.one': '{n} palavra para rever na próxima revisão.',
  'review.wordsToReview.other': '{n} palavras para rever na próxima revisão.',
  'review.next': 'Próxima revisão',
  'review.backToCourse': 'Voltar ao curso',
  'review.noRounds': 'Neste curso não há rondas para rever.',
  // Build 265: Word Lookup.
  'wordLookup.note': 'Uma das traduções possíveis, do GuideBook deste curso.',
  'wordLookup.notes':
      'Algumas das traduções possíveis, do GuideBook deste curso.',
  'wordLookup.notice':
      'Toque numa palavra sublinhada a pontilhado para ver uma tradução do GuideBook deste curso. Só alguns tipos de exercício as têm. É uma ajuda, uma tradução possível: nem sempre corresponde à resposta do exercício.',
  'wordLookup.action': 'Vocabulário deste texto',
};
