/// The Spanish buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelEs = <String, String>{
  'check': 'Comprobar',
  'checkMatches': 'Comprobar parejas',
  'continue': 'Continuar',
  'testResults': 'Resultados de la prueba · {percent}%',
  'testPassed': 'Aprobado · {percent}%',
  'testBelowThreshold': 'Por debajo del umbral de aprobado · {percent}%',
  'testQuestion': 'Pregunta {n}: {status}',
  'testNextQuestion': 'Siguiente pregunta',
  'testSeeResults': 'Ver resultados',
  'correct': 'Correcto',
  'incorrect': 'Incorrecto',
  'hint': 'Pista: {hint}',
  'yourAnswer': 'Tu respuesta',
  'missingWord': 'Palabra que falta',
  'missingLetters': 'Letras que faltan',
  'correctAnswer': 'Respuesta correcta: {answer}',
  'correctAnswerLabel': 'Respuesta correcta:',
  'correctTranslations': 'Traducciones correctas:',
  'otherCorrectTranslations': 'Otras traducciones correctas:',
  'somePossibleTranslations': 'Algunas traducciones posibles:',
  'acceptedDifference': 'Diferencia aceptada: {list}',
  'acceptedDifferences': 'Diferencias aceptadas: {list}',
  'seeCourseAnswer': 'Consulta la respuesta del curso.',
  'reviewTheFlashcard': 'Repasa la tarjeta.',
  'playAudio': 'Reproducir audio',
  'playAudioAgain': 'Volver a reproducir',
  'playSound': 'Reproducir sonido',
  'play': 'Reproducir',
  'audioUnavailable': 'Audio no disponible',
  'audioOffNote':
      'El audio está desactivado o no disponible. El ejercicio funciona igualmente.',
  'audioNotOnDevice': 'Audio no disponible en este dispositivo.',
  'listenToAnswer': 'Escucha la respuesta',
  'listenFirst': 'Escucha primero…',
  'listen': 'Escucha…',
  'usage': 'Uso:',
  'pronounceWord': 'Pronunciar la palabra o frase',
  'pronounceUsage': 'Pronunciar la frase de ejemplo',
  'reviewAgain': 'Repasar otra vez',
  'gotIt': 'Entendido',
  'cardAgainLater': 'Esta tarjeta volverá a aparecer más tarde en esta ronda.',
  'cardReviewed': 'Tarjeta repasada.',
  'linkNotOpened': 'No se pudo abrir el enlace.',
  'empty': 'Vacío',
  'nothingHereYet': 'Aún no hay nada',
  'slotNumber': 'Hueco {n}',
  'gapNumber': 'Espacio {n}',
  'groupNumber': 'Grupo {n}',
  'beforeYouStart': 'Antes de empezar',
  'openGuidebook': 'Abrir la guía',
  'continueToRound': 'Ir a la ronda',
  'lessonLine': '{language} · Lección {n} · {title}',
  'roundInReview': '{round} · Repaso',
  'reviewOfRound': 'Repaso · {round}',
  'reviewingMissed': 'Repasando los ejercicios que fallaste',
  'reviewMistakesTitle': 'Repasa tus errores',
  'reviewMistakesBody': 'Volvamos a intentar los ejercicios que fallaste.',
  'reviewMistakes': 'Repasar errores',
  'finish.round': 'Terminar la ronda',
  'finish.story': 'Terminar la historia',
  'finish.sequence': 'Terminar la secuencia',
  'finishing.round': 'Terminando la ronda…',
  'finishing.story': 'Terminando la historia…',
  'finishing.sequence': 'Terminando la secuencia…',
  'leave.round': 'Salir de la ronda',
  'leave.story': 'Salir de la historia',
  'leave.sequence': 'Salir de la secuencia',
  'completed.round': 'Ronda completada',
  'completed.story': 'Historia completada',
  'completed.sequence': 'Secuencia completada',
  'nothingToScore.round': 'Nada que puntuar en esta ronda.',
  'nothingToScore.story': 'Nada que puntuar en esta historia.',
  'nothingToScore.sequence': 'Nada que puntuar en esta secuencia.',
  'steps.round': 'Ronda · {n} pasos',
  'steps.story': 'Historia · {n} pasos',
  'steps.sequence': 'Secuencia · {n} pasos',
  'summary.correctAnswers': 'Respuestas correctas: {correct}/{total} — {xp} XP',
  'summary.difficultyBonus': 'Bonificación por dificultad: +{xp} XP',
  'summary.onTimeBonus': 'Bonificación por terminar a tiempo: +{xp} XP',
  'timed.timeLeft': 'Tiempo restante: {time}',
  'timed.timeUp': 'Se acabó el tiempo',
  'timed.incomplete':
      'Este Round está incompleto. Las actividades sin responder siguen así.',
  'timed.correctXpKept': 'XP conservados por respuestas correctas: {xp}',
  'timed.retrySaving': 'Reintentar guardar los XP',
  'timed.retry': 'Reintentar Round',
  'summary.perfectBonus': 'Bonificación por ronda perfecta: +{xp} XP',
  'summary.firstLaurel': 'Primer laurel: +{xp} XP',
  'summary.lessonCompleted': 'Lección completada: +{xp} XP',
  'summary.total': 'Total: {xp} XP',
  'weeklyGoalReached': '¡Objetivo semanal alcanzado!',
  'duel.title': 'Duelo de idiomas',
  'duel.finalTitle': 'Duelo final',
  'duel.question': 'Pregunta {n}/{total} · 4 vidas',
  'duel.listenChooseMeaning': 'Escucha y elige el significado.',
  'duel.finishing': 'Terminando el duelo…',
  'duel.finish': 'Terminar el duelo',
  'duel.finalCompleted': '¡Duelo final completado!',
  'duel.won': 'Duelo ganado',
  'duel.lost': 'Duelo perdido',
  'duel.wonBody':
      'Duelo ganado: +{xp} XP\n\nHas demostrado lo que sabes. La siguiente lección ya puede desbloquearse.',
  'duel.lostLives': 'Duelo perdido. Has perdido las cuatro vidas.',
  'duel.endedEarly': 'El duelo terminó antes de completar las 25 preguntas.',
  'duel.backToCourse': 'Volver al curso',
  'review.title': 'Repaso',
  'review.beforeRound': 'Antes de la ronda',
  'review.afterRound': 'Después de la ronda',
  'review.lesson': 'Lección {n}: {title}',
  'review.round': 'Ronda {n}',
  'review.word': 'Palabra {i} de {n}',
  'review.showAnswer': 'Mostrar respuesta',
  'review.nowIKnow': 'Ya me la sé',
  'review.iKnowIt': 'Me la sé',
  'review.stillDontKnow': 'Todavía no me la sé',
  'review.showAgain': 'Muéstramela otra vez',
  'review.completed': '¡Repaso completado!',
  'review.ready': 'Listo para repasar',
  'review.noMoreRounds': 'No quedan más rondas en esta sesión de repaso.',
  'review.wordsToReview.one': '{n} palabra para repasar en el próximo repaso.',
  'review.wordsToReview.other':
      '{n} palabras para repasar en el próximo repaso.',
  'review.next': 'Siguiente repaso',
  'review.backToCourse': 'Volver al curso',
  'review.noRounds': 'En este curso no hay rondas para repasar.',
  // Build 265: Word Lookup.
  'wordLookup.note':
      'Una de las traducciones posibles, del GuideBook del curso.',
  'wordLookup.notes':
      'Algunas de las traducciones posibles, del GuideBook del curso.',
  'wordLookup.notice':
      'Toca una palabra subrayada con puntos para ver una traducción del GuideBook del curso. Solo algunos tipos de ejercicio las tienen. Es una ayuda, una traducción posible: no siempre coincide con la respuesta del ejercicio.',
  'wordLookup.action': 'Vocabulario de este texto',
};
