/// The Dutch buttons and messages of the learner panel (Build 260
/// Revision 1); AI-written, pending native review.
const learnerPanelNl = <String, String>{
  'check': 'Controleren',
  'checkMatches': 'Paren controleren',
  'continue': 'Doorgaan',
  'correct': 'Goed',
  'incorrect': 'Fout',
  'hint': 'Tip: {hint}',
  'yourAnswer': 'Jouw antwoord',
  'missingWord': 'Ontbrekend woord',
  'missingLetters': 'Ontbrekende letters',
  'correctAnswer': 'Juiste antwoord: {answer}',
  'correctAnswerLabel': 'Juiste antwoord:',
  'correctTranslations': 'Juiste vertalingen:',
  'otherCorrectTranslations': 'Andere juiste vertalingen:',
  'somePossibleTranslations': 'Enkele mogelijke vertalingen:',
  'acceptedDifference': 'Geaccepteerd verschil: {list}',
  'acceptedDifferences': 'Geaccepteerde verschillen: {list}',
  'seeCourseAnswer': 'Zie het antwoord in de cursus.',
  'reviewTheFlashcard': 'Bekijk de kaart nog eens.',
  'playAudio': 'Audio afspelen',
  'playAudioAgain': 'Opnieuw afspelen',
  'playSound': 'Geluid afspelen',
  'play': 'Afspelen',
  'audioUnavailable': 'Audio niet beschikbaar',
  'audioOffNote':
      'Audio staat uit of is niet beschikbaar. De oefening werkt toch.',
  'audioNotOnDevice': 'Audio niet beschikbaar op dit apparaat.',
  'listenToAnswer': 'Luister naar het antwoord',
  'listenFirst': 'Eerst luisteren…',
  'listen': 'Luister…',
  'usage': 'Gebruik:',
  'pronounceWord': 'Woord of zin uitspreken',
  'pronounceUsage': 'Voorbeeldzin uitspreken',
  'reviewAgain': 'Nog eens herhalen',
  'gotIt': 'Begrepen',
  'cardAgainLater': 'Deze kaart komt later in deze ronde terug.',
  'cardReviewed': 'Kaart herhaald.',
  'linkNotOpened': 'De link kon niet worden geopend.',
  'empty': 'Leeg',
  'nothingHereYet': 'Nog niets',
  'slotNumber': 'Vak {n}',
  'gapNumber': 'Gat {n}',
  'groupNumber': 'Groep {n}',
  'beforeYouStart': 'Voordat je begint',
  'openGuidebook': 'Gids openen',
  'continueToRound': 'Naar de ronde',
  'lessonLine': '{language} · Les {n} · {title}',
  'roundInReview': '{round} · Herhaling',
  'reviewOfRound': 'Herhaling · {round}',
  'reviewingMissed': 'Herhaling van de oefeningen die je fout had',
  'reviewMistakesTitle': 'Bekijk je fouten opnieuw',
  'reviewMistakesBody':
      'Laten we de oefeningen die je fout had nog eens proberen.',
  'reviewMistakes': 'Fouten herhalen',
  'finish.round': 'Ronde afronden',
  'finish.story': 'Verhaal afronden',
  'finish.sequence': 'Reeks afronden',
  'finishing.round': 'Ronde wordt afgerond…',
  'finishing.story': 'Verhaal wordt afgerond…',
  'finishing.sequence': 'Reeks wordt afgerond…',
  'leave.round': 'Ronde verlaten',
  'leave.story': 'Verhaal verlaten',
  'leave.sequence': 'Reeks verlaten',
  'completed.round': 'Ronde voltooid',
  'completed.story': 'Verhaal voltooid',
  'completed.sequence': 'Reeks voltooid',
  'nothingToScore.round': 'Niets te scoren in deze ronde.',
  'nothingToScore.story': 'Niets te scoren in dit verhaal.',
  'nothingToScore.sequence': 'Niets te scoren in deze reeks.',
  'steps.round': 'Ronde · {n} stappen',
  'steps.story': 'Verhaal · {n} stappen',
  'steps.sequence': 'Reeks · {n} stappen',
  'summary.correctAnswers': 'Goede antwoorden: {correct}/{total} — {xp} XP',
  'summary.perfectBonus': 'Perfectbonus: +{xp} XP',
  'summary.firstLaurel': 'Eerste lauwerkrans: +{xp} XP',
  'summary.lessonCompleted': 'Les voltooid: +{xp} XP',
  'summary.total': 'Totaal: {xp} XP',
  'weeklyGoalReached': 'Weekdoel bereikt!',
  'duel.title': 'Taalduel',
  'duel.finalTitle': 'Eindduel',
  'duel.question': 'Vraag {n}/{total} · 4 levens',
  'duel.listenChooseMeaning': 'Luister en kies de betekenis.',
  'duel.finishing': 'Duel wordt afgerond…',
  'duel.finish': 'Duel afronden',
  'duel.finalCompleted': 'Eindduel voltooid!',
  'duel.won': 'Duel gewonnen',
  'duel.lost': 'Duel verloren',
  'duel.wonBody':
      'Duel gewonnen: +{xp} XP\n\nJe hebt laten zien wat je kunt. De volgende les kan nu worden ontgrendeld.',
  'duel.lostLives': 'Duel verloren. Je bent alle vier levens kwijt.',
  'duel.endedEarly':
      'Het duel eindigde voordat alle 25 vragen waren beantwoord.',
  'duel.backToCourse': 'Terug naar de cursus',
  'review.title': 'Herhaling',
  'review.beforeRound': 'Voor de ronde',
  'review.afterRound': 'Na de ronde',
  'review.lesson': 'Les {n}: {title}',
  'review.round': 'Ronde {n}',
  'review.word': 'Woord {i} van {n}',
  'review.showAnswer': 'Antwoord tonen',
  'review.nowIKnow': 'Nu ken ik het',
  'review.iKnowIt': 'Ik ken het',
  'review.stillDontKnow': 'Ik ken het nog niet',
  'review.showAgain': 'Laat het me nog eens zien',
  'review.completed': 'Herhaling voltooid!',
  'review.ready': 'Klaar om te herhalen',
  'review.noMoreRounds': 'Er zijn geen rondes meer in deze herhaalsessie.',
  'review.wordsToReview.one':
      '{n} woord om te herhalen in de volgende herhaling.',
  'review.wordsToReview.other':
      '{n} woorden om te herhalen in de volgende herhaling.',
  'review.next': 'Volgende herhaling',
  'review.backToCourse': 'Terug naar de cursus',
  'review.noRounds': 'Deze cursus heeft geen rondes om te herhalen.',
};
