/// The Portuguese exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyPt = <String, String>{
  'type.default': 'EXERCÍCIO',
  'type.inputMissingWord': 'ESCREVE A PALAVRA EM FALTA',
  'type.selectCharacter': 'RECONHECE CARACTERES',
  'type.select': 'ESCOLHER',
  'type.selectListen': 'OUVIR E ESCOLHER',
  'type.selectListenPassage': 'COMPREENSÃO ORAL',
  'type.selectRead': 'LEITURA',
  'type.selectDialogue': 'DIÁLOGO',
  'type.selectImage': 'ESCOLHER A IMAGEM',
  'type.presentation': 'CARTÃO',
  'type.dialogueLine': 'DIÁLOGO',
  'type.storyCover': 'HISTÓRIA',
  'type.inputComplete': 'COMPLETAR',
  'type.selectComplete': 'COMPLETAR A FRASE',
  'type.arrangeSentence': 'FORMAR A FRASE',
  'type.arrangeLines': 'ORDENAR AS FRASES',
  'type.arrangeWord': 'FORMAR A PALAVRA',
  'type.inputPictureName': 'NOMEIE O QUE VÊ',
  'type.arrangePictureName': 'NOMEIE O QUE VÊ',
  'type.matchTranslation': 'ASSOCIAR',
  'type.match': 'ASSOCIAR',
  'type.inputListenGaps': 'COMPLETAR',
  'type.inputListenWrite': 'ESCREVER O QUE OUVE',
  'type.matchAudio': 'ASSOCIAR O ÁUDIO',
  'instruction.default': 'Complete o exercício.',
  'instruction.inputMissingWord':
      'A primeira letra é dada: escreva a palavra inteira.',
  'instruction.selectCharacter': 'Escolhe a opção que corresponde ao carácter.',
  'instruction.select': 'Encontre a resposta correta.',
  'instruction.selectListen':
      'Encontre a resposta que corresponde ao que ouve.',
  'instruction.selectListenPassage': 'Ouça e escolha a resposta correta.',
  'instruction.selectRead': 'Leia e escolha a resposta correta.',
  'instruction.selectDialogue': 'Leia o diálogo e escolha a melhor resposta.',
  'instruction.selectImage': 'Encontre a imagem correspondente.',
  'instruction.presentation': 'Estude a palavra e o seu uso.',
  'instruction.dialogueLine': 'Leia ou ouça, depois continue.',
  'instruction.dialogueLineText': 'Leia, depois continue.',
  'instruction.dialogueLineAudio': 'Ouça, depois continue.',
  'instruction.dialogueLineAfterAudio':
      'Ouça primeiro; o texto aparece depois.',
  'instruction.storyCover':
      'Começa uma história. Continue quando estiver pronto.',
  'instruction.inputComplete': 'Escreva as palavras que completam a frase.',
  'instruction.selectComplete': 'Escolha o bloco que encaixa na lacuna.',
  'instruction.select_opposite': 'Encontre o oposto.',
  'instruction.arrangeSentence': 'Coloque as palavras na ordem correta.',
  'instruction.arrangeLines': 'Coloque as linhas numa ordem lógica.',
  'instruction.arrangeWord': 'Soletre o que a imagem mostra.',
  'instruction.inputPictureName': 'Escreva o nome da imagem.',
  'instruction.arrangePictureName': 'Ordene os blocos para nomear a imagem.',
  'instruction.matchTranslation': 'Emparelhe cada palavra com a sua tradução.',
  'instruction.match': 'Emparelhe os elementos que andam juntos.',
  'type.assignGroups': 'ORDENAR EM GRUPOS',
  'type.assignSlots': 'PREENCHER AS CASAS',
  'type.assignGaps': 'PREENCHER AS LACUNAS',
  'instruction.assignGroups':
      'Toque num item e depois no grupo a que pertence.',
  'instruction.assignSlots': 'Toque num item e depois na sua casa.',
  'instruction.assignGaps':
      'Toque numa palavra e depois na lacuna que ela preenche.',
  'instruction.inputListenGaps': 'Ouça e complete a palavra em falta.',
  'instruction.inputListenWrite': 'Escreva cada palavra que ouve.',
  'instruction.matchAudio': 'Emparelhe cada áudio com a sua palavra.',
  'type.inputTranslation': 'ESCREVER A TRADUÇÃO',
  'type.arrangeTranslation': 'FORMAR A TRADUÇÃO',
  'type.selectContext': 'CONTEXTO',
  'instruction.inputTranslation': 'Traduza para {language}.',
  'instruction.arrangeTranslation':
      'Traduza para {language} com os blocos de palavras.',
  'instruction.selectContext':
      'Use o contexto para escolher a resposta correta.',
  'instruction.inputCompleteOne': 'Escreva a palavra que completa a frase.',
  'instruction.inputCompleteLetters': 'Escreva as letras que faltam.',
  'instruction.selectListenQuestion': 'Ouça e responda à pergunta.',
  'instruction.selectListenHeard': 'Selecione a frase que ouviu.',
  'instruction.selectListenMeaning': 'Selecione o significado do que ouviu.',
  'type.selectPicture': 'O QUE HÁ NA IMAGEM?',
  'instruction.selectPicture': 'Escolha a opção mais adequada.',
  'instruction.arrangeWordHeard': 'Soletre a palavra que ouve.',
  'instruction.arrangeWordClue': 'Soletre a palavra que a pista descreve.',
  'instruction.arrangeGaps': 'Escolha uma palavra para cada lacuna.',
  'type.selectCompleteAll': 'UMA PALAVRA PARA TODAS',
  'instruction.selectCompleteAll':
      'Escolha a palavra que preenche todas as lacunas.',
};
