/// The Dutch exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyNl = <String, String>{
  'type.default': 'OEFENING',
  'type.inputMissingWord': 'VUL HET ONTBREKENDE WOORD AAN',
  'type.selectCharacter': 'HERKEN TEKENS',
  'type.select': 'KIEZEN',
  'type.selectListen': 'LUISTER EN KIES',
  'type.selectListenPassage': 'LUISTEREN',
  'type.selectRead': 'LEZEN',
  'type.selectDialogue': 'DIALOOG',
  'type.selectImage': 'KIES DE AFBEELDING',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOOG',
  'type.storyCover': 'VERHAAL',
  'type.inputComplete': 'AANVULLEN',
  'type.selectComplete': 'ZIN AANVULLEN',
  'type.arrangeSentence': 'MAAK DE ZIN',
  'type.arrangeLines': 'ZET DE ZINNEN OP VOLGORDE',
  'type.arrangeWord': 'MAAK HET WOORD',
  'type.inputPictureName': 'BENOEM WAT JE ZIET',
  'type.arrangePictureName': 'BENOEM WAT JE ZIET',
  'type.matchTranslation': 'KOPPELEN',
  'type.match': 'KOPPELEN',
  'type.inputListenGaps': 'AANVULLEN',
  'type.inputListenWrite': 'SCHRIJF WAT JE HOORT',
  'type.matchAudio': 'KOPPEL DE AUDIO',
  'instruction.default': 'Maak de oefening.',
  'instruction.inputMissingWord':
      'De eerste letter staat er al: typ het hele woord.',
  'instruction.selectCharacter': 'Kies de optie die bij het teken hoort.',
  'instruction.select': 'Zoek het juiste antwoord.',
  'instruction.selectListen': 'Zoek het antwoord dat past bij wat je hoort.',
  'instruction.selectListenPassage': 'Luister en kies het juiste antwoord.',
  'instruction.selectRead': 'Lees en kies het juiste antwoord.',
  'instruction.selectDialogue': 'Lees de dialoog en kies het beste antwoord.',
  'instruction.selectImage': 'Zoek de bijpassende afbeelding.',
  'instruction.presentation': 'Bestudeer het woord en het gebruik ervan.',
  'instruction.dialogueLine': 'Lees of luister, en ga dan verder.',
  'instruction.dialogueLineText': 'Lees, en ga dan verder.',
  'instruction.dialogueLineAudio': 'Luister, en ga dan verder.',
  'instruction.dialogueLineAfterAudio':
      'Luister eerst; de tekst verschijnt daarna.',
  'instruction.storyCover':
      'Er begint een verhaal. Ga verder als je klaar bent.',
  'instruction.inputComplete': 'Typ de woorden die de zin aanvullen.',
  'instruction.selectComplete': 'Kies het blok dat in het gat past.',
  'instruction.select_opposite': 'Zoek het tegenovergestelde.',
  'instruction.arrangeSentence': 'Zet de woorden in de juiste volgorde.',
  'instruction.arrangeLines': 'Zet de regels in een logische volgorde.',
  'instruction.arrangeWord': 'Spel wat de afbeelding toont.',
  'instruction.inputPictureName': 'Typ de naam van de afbeelding.',
  'instruction.arrangePictureName':
      'Zet de blokken op volgorde om de afbeelding te benoemen.',
  'instruction.matchTranslation': 'Zet elk woord bij zijn vertaling.',
  'instruction.match': 'Zet de items bij elkaar die bij elkaar horen.',
  'type.assignGroups': 'IN GROEPEN SORTEREN',
  'type.assignSlots': 'VAKJES VULLEN',
  'type.assignGaps': 'GATEN VULLEN',
  'instruction.assignGroups':
      'Tik op een item en dan op de groep waar het bij hoort.',
  'instruction.assignSlots': 'Tik op een item en dan op zijn vakje.',
  'instruction.assignGaps': 'Tik op een woord en dan op het gat dat het vult.',
  'instruction.inputListenGaps': 'Luister en vul het ontbrekende woord aan.',
  'instruction.inputListenWrite': 'Typ elk woord dat je hoort.',
  'instruction.matchAudio': 'Zet elk geluid bij zijn woord.',
  'type.inputTranslation': 'TYPE DE VERTALING',
  'type.arrangeTranslation': 'MAAK DE VERTALING',
  'type.selectContext': 'CONTEXT',
  'instruction.inputTranslation': 'Vertaal naar het {language}.',
  'instruction.arrangeTranslation':
      'Vertaal naar het {language} met de woordblokken.',
  'instruction.selectContext':
      'Gebruik de context om het juiste antwoord te kiezen.',
  'instruction.inputCompleteOne': 'Typ het woord dat de zin aanvult.',
  'instruction.inputCompleteLetters': 'Typ de ontbrekende letters.',
  'instruction.selectListenQuestion': 'Luister en beantwoord de vraag.',
  'instruction.selectListenHeard': 'Kies de zin die je hebt gehoord.',
  'instruction.selectListenMeaning':
      'Kies de betekenis van wat je hebt gehoord.',
  'type.selectPicture': 'WAT IS ER OP DE AFBEELDING?',
  'instruction.selectPicture': 'Kies de optie die het best past.',
  'instruction.arrangeWordHeard': 'Spel het woord dat je hoort.',
  'instruction.arrangeWordClue': 'Spel het woord dat de hint beschrijft.',
  'instruction.arrangeGaps': 'Kies een woord voor elk gat.',
  'type.selectCompleteAll': 'ÉÉN WOORD VOOR ALLES',
  'instruction.selectCompleteAll': 'Kies het woord dat in elk gat past.',
};
