/// The Dutch exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyNl = <String, String>{
  'type.default': 'OEFENING',
  'type.inputMissingWord': 'VUL HET ONTBREKENDE WOORD AAN',
  'type.selectCharacter': 'HERKEN TEKENS',
  'type.select': 'KIEZEN',
  'type.selectListen': 'LUISTER EN KIES',
  'type.selectListenPassage': 'LUISTEREN',
  'type.selectRead': 'LEZEN',
  'type.selectDialogue': 'DIALOOG',
  'type.selectImage': 'KIES DE AFBEELDING',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOOG',
  'type.storyCover': 'VERHAAL',
  'type.inputComplete': 'AANVULLEN',
  'type.selectComplete': 'ZIN AANVULLEN',
  'type.arrangeSentence': 'MAAK DE ZIN',
  'type.arrangeLines': 'ZET DE ZINNEN OP VOLGORDE',
  'type.arrangeWord': 'MAAK HET WOORD',
  'type.inputPictureName': 'BENOEM WAT JE ZIET',
  'type.arrangePictureName': 'BENOEM WAT JE ZIET',
  'type.matchTranslation': 'KOPPELEN',
  'type.match': 'KOPPELEN',
  'type.inputListenGaps': 'AANVULLEN',
  'type.inputListenWrite': 'SCHRIJF WAT JE HOORT',
  'type.matchAudio': 'KOPPEL DE AUDIO',
  'instruction.default': 'Maak de oefening.',
  'instruction.inputMissingWord':
      'De eerste letter staat er al: typ het hele woord.',
  'instruction.selectCharacter': 'Kies de optie die bij het teken hoort.',
  'instruction.select': 'Zoek het juiste antwoord.',
  'instruction.selectListen': 'Zoek het antwoord dat past bij wat je hoort.',
  'instruction.selectListenPassage': 'Luister en kies het juiste antwoord.',
  'instruction.selectRead': 'Lees en kies het juiste antwoord.',
  'instruction.selectDialogue': 'Lees de dialoog en kies het beste antwoord.',
  'instruction.selectImage': 'Zoek de bijpassende afbeelding.',
  'instruction.presentation': 'Bestudeer het woord en het gebruik ervan.',
  'instruction.dialogueLine': 'Lees of luister, en ga dan verder.',
  'instruction.dialogueLineText': 'Lees, en ga dan verder.',
  'instruction.dialogueLineAudio': 'Luister, en ga dan verder.',
  'instruction.dialogueLineAfterAudio':
      'Luister eerst; de tekst verschijnt daarna.',
  'instruction.storyCover':
      'Er begint een verhaal. Ga verder als je klaar bent.',
  'instruction.inputComplete': 'Typ de woorden die de zin aanvullen.',
  'instruction.selectComplete': 'Selecteer het blok dat in het gat past.',
  'instruction.select_opposite': 'Zoek het tegenovergestelde.',
  'instruction.arrangeSentence': 'Breng de woorden in de juiste volgorde.',
  'instruction.arrangeLines': 'Breng de regels in een logische volgorde.',
  'instruction.arrangeWord': 'Bouw het woord dat de afbeelding toont.',
  'instruction.inputPictureName': 'Schrijf de naam van de afbeelding.',
  'instruction.arrangePictureName':
      'Zet de blokken op volgorde om de afbeelding te benoemen.',
  'instruction.matchTranslation': 'Zet elk woord bij zijn vertaling.',
  'instruction.match': 'Zet de items bij elkaar die bij elkaar horen.',
  'type.assignGroups': 'IN GROEPEN SORTEREN',
  'type.assignSlots': 'VAKJES VULLEN',
  'type.assignGaps': 'GATEN VULLEN',
  'instruction.assignGroups':
      'Tik op een item en dan op de groep waar het bij hoort.',
  'instruction.assignSlots': 'Tik op een item en dan op zijn vakje.',
  'instruction.assignGaps': 'Tik op een woord en dan op het gat dat het vult.',
  'instruction.inputListenGaps': 'Maak het ontbrekende woord af dat je hoort.',
  'instruction.inputListenWrite': 'Typ elk woord dat je hoort.',
  'instruction.matchAudio': 'Zet elk geluid bij zijn woord.',
  'type.inputTranslation': 'TYPE DE VERTALING',
  'type.arrangeTranslation': 'MAAK DE VERTALING',
  'type.selectContext': 'CONTEXT',
  'instruction.inputTranslation': 'Vertaal naar het {language}.',
  'instruction.arrangeTranslation':
      'Vertaal naar het {language} met de woordblokken.',
  'instruction.selectContext':
      'Gebruik de context om het juiste antwoord te kiezen.',
  'instruction.inputCompleteOne': 'Typ het woord dat de zin aanvult.',
  'instruction.inputCompleteLetters': 'Typ de ontbrekende letters.',
  'instruction.selectListenQuestion': 'Beantwoord de vraag over wat je hoort.',
  'instruction.selectListenHeard': 'Kies de zin die je hebt gehoord.',
  'instruction.selectListenMeaning':
      'Kies de betekenis van wat je hebt gehoord.',
  'type.selectPicture': 'WAT IS ER OP DE AFBEELDING?',
  'instruction.selectPicture': 'Kies de optie die het best past.',
  'instruction.arrangeWordHeard': 'Bouw het woord dat je hoort.',
  'instruction.arrangeWordClue': 'Bouw het woord dat de hint beschrijft.',
  'instruction.arrangeGaps': 'Zet een woord in elk gat.',
  'type.selectCompleteAll': 'ÉÉN WOORD VOOR ALLES',
  'instruction.selectCompleteAll': 'Kies het woord dat in elk gat past.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'KIES DE VERTALING',
  'title.type_the_translation': 'TYPE DE VERTALING',
  'title.build_the_translation': 'MAAK DE VERTALING',
  'title.match_the_words': 'KOPPEL DE WOORDEN',
  'title.match_by_meaning': 'KOPPEL OP BETEKENIS',
  'title.flashcard': 'FLASHCARD',
  'title.picture_flashcard': 'FLASHCARD MET AFBEELDING',
  'title.choose_the_answer': 'KIES HET ANTWOORD',
  'title.pick_the_missing_word': 'KIES HET ONTBREKENDE WOORD',
  'title.type_the_missing_word': 'VUL HET ONTBREKENDE WOORD AAN',
  'title.word_order': 'WOORDVOLGORDE',
  'title.true_or_false': 'WAAR OF NIET WAAR',
  'title.pick_the_words_for_the_gaps': 'KIES DE WOORDEN VOOR DE GATEN',
  'title.one_word_fills_all': 'ÉÉN WOORD VOOR ALLES',
  'title.complete_the_text': 'VUL DE TEKST AAN',
  'title.missing_letters': 'ONTBREKENDE LETTERS',
  'title.put_the_sentences_in_order': 'ZET DE ZINNEN OP VOLGORDE',
  'title.sort_into_groups': 'IN GROEPEN SORTEREN',
  'title.fill_the_slots': 'VAKJES VULLEN',
  'title.listen_and_choose': 'LUISTER EN KIES',
  'title.listen_and_answer': 'LUISTER EN ANTWOORD',
  'title.type_what_you_hear': 'SCHRIJF WAT JE HOORT',
  'title.listen_and_fill_the_gaps': 'LUISTER EN VUL DE GATEN',
  'title.listen_and_match': 'LUISTER EN KOPPEL',
  'title.listen_and_pick_the_image': 'LUISTER EN KIES DE AFBEELDING',
  'title.spell_what_you_hear': 'SPEL WAT JE HOORT',
  'title.read_and_answer': 'LEES EN ANTWOORD',
  'title.select_the_image': 'KIES DE AFBEELDING',
  'title.recognize_characters': 'HERKEN TEKENS',
  'title.spell_the_word_in_the_picture': 'SPEL HET WOORD BIJ DE AFBEELDING',
  'title.what_is_in_the_picture': 'WAT IS ER OP DE AFBEELDING?',
  'title.type_what_you_see': 'TYP WAT JE ZIET',
  'title.name_what_you_see': 'BENOEM WAT JE ZIET',
  'title.spell_the_word': 'SPEL HET WOORD',
  'title.match_pictures_to_words': 'KOPPEL AFBEELDINGEN AAN WOORDEN',
  'title.note_card': 'NOTITIEKAART',
  'title.dialogue_line': 'DIALOOGREGEL',
  'title.story_cover': 'VERHAALOMSLAG',
  'title.before_you_start': 'VOORDAT JE BEGINT',
  'title.page': 'PAGINA',
  'instruction.selectTranslation':
      'Selecteer de juiste vertaling naar het {language}',
};
