/// The German exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyDe = <String, String>{
  'type.default': 'ÜBUNG',
  'type.inputMissingWord': 'ERGÄNZE DAS WORT',
  'type.selectCharacter': 'ZEICHEN ERKENNEN',
  'type.select': 'AUSWÄHLEN',
  'type.selectListen': 'HÖREN UND AUSWÄHLEN',
  'type.selectListenPassage': 'HÖRVERSTEHEN',
  'type.selectRead': 'LESEN',
  'type.selectDialogue': 'DIALOG',
  'type.selectImage': 'BILD AUSWÄHLEN',
  'type.presentation': 'KARTE',
  'type.dialogueLine': 'DIALOG',
  'type.storyCover': 'GESCHICHTE',
  'type.inputComplete': 'ERGÄNZEN',
  'type.selectComplete': 'SATZ ERGÄNZEN',
  'type.arrangeSentence': 'SATZ BILDEN',
  'type.arrangeLines': 'SÄTZE ORDNEN',
  'type.arrangeWord': 'WORT BILDEN',
  'type.inputPictureName': 'BENENNE, WAS DU SIEHST',
  'type.arrangePictureName': 'BENENNE, WAS DU SIEHST',
  'type.matchTranslation': 'ZUORDNEN',
  'type.match': 'ZUORDNEN',
  'type.inputListenGaps': 'ERGÄNZEN',
  'type.inputListenWrite': 'SCHREIBEN, WAS DU HÖRST',
  'type.matchAudio': 'AUDIO ZUORDNEN',
  'instruction.default': 'Bearbeite die Übung.',
  'instruction.inputMissingWord':
      'Der erste Buchstabe ist vorgegeben: Schreibe das ganze Wort.',
  'instruction.selectCharacter': 'Wähle die Option, die zum Zeichen passt.',
  'instruction.select': 'Finde die richtige Antwort.',
  'instruction.selectListen':
      'Finde die Antwort, die zu dem passt, was du hörst.',
  'instruction.selectListenPassage': 'Höre zu und wähle die richtige Antwort.',
  'instruction.selectRead': 'Lies und wähle die richtige Antwort.',
  'instruction.selectDialogue': 'Lies den Dialog und wähle die beste Antwort.',
  'instruction.selectImage': 'Finde das passende Bild.',
  'instruction.presentation': 'Lerne das Wort und seine Verwendung.',
  'instruction.dialogueLine': 'Lies oder höre zu, dann weiter.',
  'instruction.dialogueLineText': 'Lies, dann weiter.',
  'instruction.dialogueLineAudio': 'Hör zu, dann weiter.',
  'instruction.dialogueLineAfterAudio':
      'Hör zuerst zu; der Text erscheint danach.',
  'instruction.storyCover':
      'Eine Geschichte beginnt. Weiter, wenn du bereit bist.',
  'instruction.inputComplete':
      'Schreibe die Wörter, die den Satz vervollständigen.',
  'instruction.selectComplete': 'Wähle den Baustein, der in die Lücke passt.',
  'instruction.select_opposite': 'Finde das Gegenteil.',
  'instruction.arrangeSentence':
      'Bringe die Wörter in die richtige Reihenfolge.',
  'instruction.arrangeLines': 'Bringe die Zeilen in eine logische Reihenfolge.',
  'instruction.arrangeWord': 'Buchstabiere, was das Bild zeigt.',
  'instruction.inputPictureName': 'Schreibe den Namen des Bildes.',
  'instruction.arrangePictureName':
      'Ordne die Bausteine, um das Bild zu benennen.',
  'instruction.matchTranslation':
      'Bilde Paare aus jedem Wort und seiner Übersetzung.',
  'instruction.match': 'Bilde Paare aus den Elementen, die zusammengehören.',
  'type.assignGroups': 'IN GRUPPEN SORTIEREN',
  'type.assignSlots': 'FELDER FÜLLEN',
  'type.assignGaps': 'LÜCKEN FÜLLEN',
  'instruction.assignGroups':
      'Tippe auf ein Element und dann auf seine Gruppe.',
  'instruction.assignSlots': 'Tippe auf ein Element und dann auf sein Feld.',
  'instruction.assignGaps':
      'Tippe auf ein Wort und dann auf die Lücke, die es füllt.',
  'instruction.inputListenGaps': 'Höre zu und ergänze das fehlende Wort.',
  'instruction.inputListenWrite': 'Schreibe jedes Wort, das du hörst.',
  'instruction.matchAudio': 'Bilde Paare aus jedem Ton und seinem Wort.',
  'type.inputTranslation': 'ÜBERSETZUNG EINGEBEN',
  'type.arrangeTranslation': 'ÜBERSETZUNG BILDEN',
  'type.selectContext': 'KONTEXT',
  'instruction.inputTranslation': 'Übersetze auf {language}.',
  'instruction.arrangeTranslation':
      'Übersetze mit den Wortbausteinen auf {language}.',
  'instruction.selectContext':
      'Nutze den Kontext, um die richtige Antwort auszuwählen.',
  'instruction.inputCompleteOne':
      'Schreibe das Wort, das den Satz vervollständigt.',
  'instruction.inputCompleteLetters': 'Schreibe die fehlenden Buchstaben.',
  'instruction.selectListenQuestion': 'Höre zu und beantworte die Frage.',
  'instruction.selectListenHeard': 'Wähle den Satz, den du gehört hast.',
  'instruction.selectListenMeaning':
      'Wähle die Bedeutung dessen, was du gehört hast.',
  'type.selectPicture': 'WAS IST AUF DEM BILD?',
  'instruction.selectPicture': 'Wähle die passendste Option.',
  'instruction.arrangeWordHeard': 'Buchstabiere das Wort, das du hörst.',
  'instruction.arrangeWordClue':
      'Buchstabiere das Wort, das der Hinweis beschreibt.',
  'instruction.arrangeGaps': 'Wähle für jede Lücke ein Wort.',
  'type.selectCompleteAll': 'EIN WORT FÜR ALLE',
  'instruction.selectCompleteAll': 'Wähle das Wort, das in jede Lücke passt.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'ÜBERSETZUNG AUSWÄHLEN',
  'title.type_the_translation': 'ÜBERSETZUNG EINGEBEN',
  'title.build_the_translation': 'ÜBERSETZUNG BILDEN',
  'title.match_the_words': 'WÖRTER ZUORDNEN',
  'title.match_by_meaning': 'NACH BEDEUTUNG ZUORDNEN',
  'title.flashcard': 'KARTE',
  'title.picture_flashcard': 'BILDKARTE',
  'title.choose_the_answer': 'ANTWORT AUSWÄHLEN',
  'title.pick_the_missing_word': 'FEHLENDES WORT AUSWÄHLEN',
  'title.type_the_missing_word': 'ERGÄNZE DAS WORT',
  'title.word_order': 'WORTSTELLUNG',
  'title.true_or_false': 'RICHTIG ODER FALSCH',
  'title.pick_the_words_for_the_gaps': 'WÖRTER FÜR DIE LÜCKEN AUSWÄHLEN',
  'title.one_word_fills_all': 'EIN WORT FÜR ALLE',
  'title.complete_the_text': 'TEXT ERGÄNZEN',
  'title.missing_letters': 'FEHLENDE BUCHSTABEN',
  'title.put_the_sentences_in_order': 'SÄTZE ORDNEN',
  'title.sort_into_groups': 'IN GRUPPEN SORTIEREN',
  'title.fill_the_slots': 'FELDER FÜLLEN',
  'title.listen_and_choose': 'HÖREN UND AUSWÄHLEN',
  'title.listen_and_answer': 'HÖREN UND ANTWORTEN',
  'title.type_what_you_hear': 'SCHREIBEN, WAS DU HÖRST',
  'title.listen_and_fill_the_gaps': 'HÖREN UND LÜCKEN FÜLLEN',
  'title.listen_and_match': 'HÖREN UND ZUORDNEN',
  'title.listen_and_pick_the_image': 'HÖREN UND BILD AUSWÄHLEN',
  'title.spell_what_you_hear': 'BUCHSTABIERE, WAS DU HÖRST',
  'title.read_and_answer': 'LESEN UND ANTWORTEN',
  'title.select_the_image': 'BILD AUSWÄHLEN',
  'title.recognize_characters': 'ZEICHEN ERKENNEN',
  'title.spell_the_word_in_the_picture': 'BUCHSTABIERE DAS WORT ZUM BILD',
  'title.what_is_in_the_picture': 'WAS IST AUF DEM BILD?',
  'title.type_what_you_see': 'SCHREIB, WAS DU SIEHST',
  'title.name_what_you_see': 'BENENNE, WAS DU SIEHST',
  'title.spell_the_word': 'BUCHSTABIERE DAS WORT',
  'title.match_pictures_to_words': 'BILDER UND WÖRTER ZUORDNEN',
  'title.note_card': 'NOTIZKARTE',
  'title.dialogue_line': 'DIALOGZEILE',
  'title.story_cover': 'TITELBILD DER GESCHICHTE',
  'title.before_you_start': 'BEVOR DU BEGINNST',
  'title.page': 'SEITE',
  'instruction.selectTranslation':
      'Wähle die richtige Übersetzung auf {language}',
};
