/// The English exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyEn = <String, String>{
  'type.default': 'EXERCISE',
  'type.inputMissingWord': 'TYPE THE MISSING WORD',
  'type.selectCharacter': 'RECOGNIZE CHARACTERS',
  'type.select': 'CHOOSE',
  'type.selectListen': 'LISTEN AND CHOOSE',
  'type.selectListenPassage': 'LISTENING',
  'type.selectRead': 'READING',
  'type.selectDialogue': 'DIALOGUE',
  'type.selectImage': 'CHOOSE THE IMAGE',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOGUE',
  'type.storyCover': 'STORY',
  'type.inputComplete': 'COMPLETE',
  'type.selectComplete': 'COMPLETE THE SENTENCE',
  'type.arrangeSentence': 'BUILD THE SENTENCE',
  'type.arrangeLines': 'PUT THE SENTENCES IN ORDER',
  'type.arrangeWord': 'BUILD THE WORD',
  'type.inputPictureName': 'NAME WHAT YOU SEE',
  'type.arrangePictureName': 'NAME WHAT YOU SEE',
  'type.matchTranslation': 'MATCH',
  'type.match': 'MATCH',
  'type.inputListenGaps': 'COMPLETE',
  'type.inputListenWrite': 'WRITE WHAT YOU HEAR',
  'type.matchAudio': 'MATCH THE AUDIO',
  'type.inputTranslation': 'TYPE THE TRANSLATION',
  'type.arrangeTranslation': 'BUILD THE TRANSLATION',
  'type.selectContext': 'CONTEXT',
  'instruction.default': 'Complete the exercise.',
  'instruction.inputMissingWord':
      'The first letter is given: type the whole word.',
  'instruction.selectCharacter':
      'Choose the option that matches the character.',
  'instruction.select': 'Find the correct answer.',
  'instruction.selectListen': 'Find the answer that matches what you hear.',
  'instruction.selectListenPassage': 'Listen and choose the correct answer.',
  'instruction.selectRead': 'Read and choose the correct answer.',
  'instruction.selectDialogue':
      'Read the dialogue and choose the best response.',
  'instruction.selectImage': 'Find the matching picture.',
  'instruction.presentation': 'Study the word and its usage.',
  'instruction.dialogueLine': 'Read or listen, then continue.',
  'instruction.dialogueLineText': 'Read, then continue.',
  'instruction.dialogueLineAudio': 'Listen, then continue.',
  'instruction.dialogueLineAfterAudio': 'Listen first; the text appears after.',
  'instruction.storyCover': 'A story begins. Continue when you are ready.',
  'instruction.inputComplete': 'Write the words that fill the gaps.',
  'instruction.selectComplete': 'Choose the block that fits the gap.',
  'instruction.select_opposite': 'Find the opposite.',
  'instruction.arrangeSentence': 'Arrange the words in the correct order.',
  'instruction.arrangeLines': 'Arrange the lines in a logical order.',
  'instruction.arrangeWord': 'Form the word the picture shows.',
  'instruction.inputPictureName': 'Write the name of the picture.',
  'instruction.arrangePictureName':
      'Put the blocks in order to name the picture.',
  'instruction.matchTranslation': 'Pair each word with its translation.',
  'instruction.match': 'Pair the items that belong together.',
  'type.assignGroups': 'SORT INTO GROUPS',
  'type.assignSlots': 'FILL THE SLOTS',
  'type.assignGaps': 'FILL THE GAPS',
  'instruction.assignGroups': 'Tap an item, then the group it belongs to.',
  'instruction.assignSlots': 'Tap an item, then its slot.',
  'instruction.assignGaps': 'Tap a word, then the gap it fills.',
  'instruction.inputListenGaps': 'Fill in the missing word you hear.',
  'instruction.inputListenWrite': 'Transcribe every word you hear.',
  'instruction.matchAudio': 'Pair each sound with its word.',
  'instruction.inputTranslation': 'Translate into {language}.',
  'instruction.arrangeTranslation':
      'Translate into {language} with the word blocks.',
  'instruction.selectContext': 'Use the context to choose the correct answer.',
  'instruction.inputCompleteOne': 'Write the word that fills the gap.',
  'instruction.inputCompleteLetters': 'Write the missing letters.',
  'instruction.selectListenQuestion':
      'Answer the question about what you hear.',
  'instruction.selectListenHeard': 'Select the sentence that you heard.',
  'instruction.selectListenMeaning': 'Select the meaning of what you heard.',
  'type.selectPicture': 'WHAT IS IN THE PICTURE?',
  'instruction.selectPicture': 'Choose the option that fits best.',
  'instruction.arrangeWordHeard': 'Form the word you hear.',
  'instruction.arrangeWordClue': 'Form the word the clue describes.',
  'instruction.arrangeGaps': 'Choose a word for each gap.',
  'type.selectCompleteAll': 'ONE WORD FILLS ALL',
  'instruction.selectCompleteAll': 'Choose the word that fills every gap.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'PICK THE TRANSLATION',
  'title.type_the_translation': 'TYPE THE TRANSLATION',
  'title.build_the_translation': 'BUILD THE TRANSLATION',
  'title.match_the_words': 'MATCH THE WORDS',
  'title.match_by_meaning': 'MATCH BY MEANING',
  'title.flashcard': 'FLASHCARD',
  'title.picture_flashcard': 'PICTURE FLASHCARD',
  'title.choose_the_answer': 'CHOOSE THE ANSWER',
  'title.pick_the_missing_word': 'PICK THE MISSING WORD',
  'title.type_the_missing_word': 'TYPE THE MISSING WORD',
  'title.word_order': 'WORD ORDER',
  'title.true_or_false': 'TRUE OR FALSE',
  'title.pick_the_words_for_the_gaps': 'PICK THE WORDS FOR THE GAPS',
  'title.one_word_fills_all': 'ONE WORD FILLS ALL',
  'title.complete_the_text': 'COMPLETE THE TEXT',
  'title.missing_letters': 'MISSING LETTERS',
  'title.put_the_sentences_in_order': 'PUT THE SENTENCES IN ORDER',
  'title.sort_into_groups': 'SORT INTO GROUPS',
  'title.fill_the_slots': 'FILL THE SLOTS',
  'title.listen_and_choose': 'LISTEN AND CHOOSE',
  'title.listen_and_answer': 'LISTEN AND ANSWER',
  'title.type_what_you_hear': 'TYPE WHAT YOU HEAR',
  'title.listen_and_fill_the_gaps': 'LISTEN AND FILL THE GAPS',
  'title.listen_and_match': 'LISTEN AND MATCH',
  'title.listen_and_pick_the_image': 'LISTEN AND PICK THE IMAGE',
  'title.spell_what_you_hear': 'SPELL WHAT YOU HEAR',
  'title.read_and_answer': 'READ AND ANSWER',
  'title.select_the_image': 'SELECT THE IMAGE',
  'title.recognize_characters': 'RECOGNIZE CHARACTERS',
  'title.spell_the_word_in_the_picture': 'SPELL THE WORD IN THE PICTURE',
  'title.what_is_in_the_picture': 'WHAT IS IN THE PICTURE?',
  'title.type_what_you_see': 'TYPE WHAT YOU SEE',
  'title.name_what_you_see': 'NAME WHAT YOU SEE',
  'title.spell_the_word': 'SPELL THE WORD',
  'title.match_pictures_to_words': 'MATCH PICTURES TO WORDS',
  'title.note_card': 'NOTE CARD',
  'title.dialogue_line': 'DIALOGUE LINE',
  'title.story_cover': 'STORY COVER',
  'title.before_you_start': 'BEFORE YOU START',
  'title.page': 'PAGE',
  'instruction.selectTranslation': 'Choose the correct {language} translation',
};
