/// The Spanish exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyEs = <String, String>{
  'type.default': 'EJERCICIO',
  'type.inputMissingWord': 'ESCRIBE LA PALABRA QUE FALTA',
  'type.selectCharacter': 'RECONOCE CARACTERES',
  'type.select': 'ELIGE',
  'type.selectListen': 'ESCUCHA Y ELIGE',
  'type.selectListenPassage': 'COMPRENSIÓN ORAL',
  'type.selectRead': 'LECTURA',
  'type.selectDialogue': 'DIÁLOGO',
  'type.selectImage': 'ELIGE LA IMAGEN',
  'type.presentation': 'TARJETA',
  'type.dialogueLine': 'DIÁLOGO',
  'type.storyCover': 'HISTORIA',
  'type.inputComplete': 'COMPLETA',
  'type.selectComplete': 'COMPLETA LA FRASE',
  'type.arrangeSentence': 'FORMA LA FRASE',
  'type.arrangeLines': 'ORDENA LAS FRASES',
  'type.arrangeWord': 'FORMA LA PALABRA',
  'type.inputPictureName': 'NOMBRA LO QUE VES',
  'type.arrangePictureName': 'NOMBRA LO QUE VES',
  'type.matchTranslation': 'RELACIONA',
  'type.match': 'RELACIONA',
  'type.inputListenGaps': 'COMPLETA',
  'type.inputListenWrite': 'ESCRIBE LO QUE OYES',
  'type.matchAudio': 'RELACIONA EL AUDIO',
  'instruction.default': 'Completa el ejercicio.',
  'instruction.inputMissingWord':
      'La primera letra ya está: escribe la palabra entera.',
  'instruction.selectCharacter': 'Elige la opción que corresponde al carácter.',
  'instruction.select': 'Encuentra la respuesta correcta.',
  'instruction.selectListen':
      'Encuentra la respuesta que corresponde a lo que oyes.',
  'instruction.selectListenPassage': 'Escucha y elige la respuesta correcta.',
  'instruction.selectRead': 'Lee y elige la respuesta correcta.',
  'instruction.selectDialogue': 'Lee el diálogo y elige la mejor respuesta.',
  'instruction.selectImage': 'Encuentra la imagen correspondiente.',
  'instruction.presentation': 'Estudia la palabra y su uso.',
  'instruction.dialogueLine': 'Lee o escucha, luego continúa.',
  'instruction.dialogueLineText': 'Lee, luego continúa.',
  'instruction.dialogueLineAudio': 'Escucha, luego continúa.',
  'instruction.dialogueLineAfterAudio':
      'Escucha primero; el texto aparece después.',
  'instruction.storyCover':
      'Empieza una historia. Continúa cuando estés listo.',
  'instruction.inputComplete': 'Escribe las palabras que completan la frase.',
  'instruction.selectComplete': 'Elige el bloque que encaja en el hueco.',
  'instruction.select_opposite': 'Encuentra el contrario.',
  'instruction.arrangeSentence': 'Pon las palabras en el orden correcto.',
  'instruction.arrangeLines': 'Ordena las líneas de forma lógica.',
  'instruction.arrangeWord': 'Deletrea lo que muestra la imagen.',
  'instruction.inputPictureName': 'Escribe el nombre de la imagen.',
  'instruction.arrangePictureName':
      'Ordena los bloques para nombrar la imagen.',
  'instruction.matchTranslation': 'Empareja cada palabra con su traducción.',
  'instruction.match': 'Empareja los elementos que van juntos.',
  'type.assignGroups': 'ORDENA EN GRUPOS',
  'type.assignSlots': 'RELLENA LAS CASILLAS',
  'type.assignGaps': 'RELLENA LOS HUECOS',
  'instruction.assignGroups':
      'Toca un elemento y luego el grupo al que pertenece.',
  'instruction.assignSlots': 'Toca un elemento y luego su casilla.',
  'instruction.assignGaps': 'Toca una palabra y luego el hueco que rellena.',
  'instruction.inputListenGaps': 'Escucha y completa la palabra que falta.',
  'instruction.inputListenWrite': 'Escribe cada palabra que oyes.',
  'instruction.matchAudio': 'Empareja cada audio con su palabra.',
  'type.inputTranslation': 'ESCRIBE LA TRADUCCIÓN',
  'type.arrangeTranslation': 'FORMA LA TRADUCCIÓN',
  'type.selectContext': 'CONTEXTO',
  'instruction.inputTranslation': 'Traduce al {language}.',
  'instruction.arrangeTranslation':
      'Traduce al {language} con los bloques de palabras.',
  'instruction.selectContext':
      'Usa el contexto para elegir la respuesta correcta.',
  'instruction.inputCompleteOne': 'Escribe la palabra que completa la frase.',
  'instruction.inputCompleteLetters': 'Escribe las letras que faltan.',
  'instruction.selectListenQuestion': 'Escucha y responde a la pregunta.',
  'instruction.selectListenHeard': 'Selecciona la frase que has oído.',
  'instruction.selectListenMeaning':
      'Selecciona el significado de lo que has oído.',
  'type.selectPicture': '¿QUÉ HAY EN LA IMAGEN?',
  'instruction.selectPicture': 'Elige la opción más adecuada.',
  'instruction.arrangeWordHeard': 'Deletrea la palabra que oyes.',
  'instruction.arrangeWordClue': 'Deletrea la palabra que describe la pista.',
  'instruction.arrangeGaps': 'Elige una palabra para cada hueco.',
  'type.selectCompleteAll': 'UNA PALABRA PARA TODOS',
  'instruction.selectCompleteAll':
      'Elige la palabra que completa todos los huecos.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'ELIGE LA TRADUCCIÓN',
  'title.type_the_translation': 'ESCRIBE LA TRADUCCIÓN',
  'title.build_the_translation': 'FORMA LA TRADUCCIÓN',
  'title.match_the_words': 'RELACIONA LAS PALABRAS',
  'title.match_by_meaning': 'RELACIONA POR SIGNIFICADO',
  'title.flashcard': 'TARJETA',
  'title.picture_flashcard': 'TARJETA CON IMAGEN',
  'title.choose_the_answer': 'ELIGE LA RESPUESTA',
  'title.pick_the_missing_word': 'ELIGE LA PALABRA QUE FALTA',
  'title.type_the_missing_word': 'ESCRIBE LA PALABRA QUE FALTA',
  'title.word_order': 'ORDEN DE LAS PALABRAS',
  'title.true_or_false': 'VERDADERO O FALSO',
  'title.pick_the_words_for_the_gaps': 'ELIGE LAS PALABRAS PARA LOS HUECOS',
  'title.one_word_fills_all': 'UNA PALABRA PARA TODOS',
  'title.complete_the_text': 'COMPLETA EL TEXTO',
  'title.missing_letters': 'LETRAS QUE FALTAN',
  'title.put_the_sentences_in_order': 'ORDENA LAS FRASES',
  'title.sort_into_groups': 'ORDENA EN GRUPOS',
  'title.fill_the_slots': 'RELLENA LAS CASILLAS',
  'title.listen_and_choose': 'ESCUCHA Y ELIGE',
  'title.listen_and_answer': 'ESCUCHA Y RESPONDE',
  'title.type_what_you_hear': 'ESCRIBE LO QUE OYES',
  'title.listen_and_fill_the_gaps': 'ESCUCHA Y RELLENA LOS HUECOS',
  'title.listen_and_match': 'ESCUCHA Y RELACIONA',
  'title.listen_and_pick_the_image': 'ESCUCHA Y ELIGE LA IMAGEN',
  'title.spell_what_you_hear': 'DELETREA LO QUE OYES',
  'title.read_and_answer': 'LEE Y RESPONDE',
  'title.select_the_image': 'ELIGE LA IMAGEN',
  'title.recognize_characters': 'RECONOCE CARACTERES',
  'title.spell_the_word_in_the_picture': 'DELETREA LA PALABRA DE LA IMAGEN',
  'title.what_is_in_the_picture': '¿QUÉ HAY EN LA IMAGEN?',
  'title.type_what_you_see': 'ESCRIBE LO QUE VES',
  'title.name_what_you_see': 'NOMBRA LO QUE VES',
  'title.spell_the_word': 'DELETREA LA PALABRA',
  'title.match_pictures_to_words': 'RELACIONA IMÁGENES Y PALABRAS',
  'title.note_card': 'NOTA',
  'title.dialogue_line': 'LÍNEA DE DIÁLOGO',
  'title.story_cover': 'PORTADA DE LA HISTORIA',
  'title.before_you_start': 'ANTES DE EMPEZAR',
  'title.page': 'PÁGINA',
  'instruction.selectTranslation': 'Elige la traducción correcta al {language}',
};
