/// The French exercise headings and instruction lines of the learner panel
/// (Build 260 Revision 0, owner decision of 1 October 2026). AI-written,
/// pending native review.
const exerciseCopyFr = <String, String>{
  'type.default': 'EXERCICE',
  'type.inputMissingWord': 'ÉCRIS LE MOT MANQUANT',
  'type.selectCharacter': 'RECONNAIS LES CARACTÈRES',
  'type.select': 'CHOISIS',
  'type.selectListen': 'ÉCOUTE ET CHOISIS',
  'type.selectListenPassage': 'COMPRÉHENSION ORALE',
  'type.selectRead': 'LECTURE',
  'type.selectDialogue': 'DIALOGUE',
  'type.selectImage': 'CHOISIS L’IMAGE',
  'type.presentation': 'CARTE',
  'type.dialogueLine': 'DIALOGUE',
  'type.storyCover': 'HISTOIRE',
  'type.inputComplete': 'COMPLÈTE',
  'type.selectComplete': 'COMPLÈTE LA PHRASE',
  'type.arrangeSentence': 'CONSTRUIS LA PHRASE',
  'type.arrangeLines': 'METS LES PHRASES DANS L’ORDRE',
  'type.arrangeWord': 'CONSTRUIS LE MOT',
  'type.inputPictureName': 'NOMME CE QUE TU VOIS',
  'type.arrangePictureName': 'NOMME CE QUE TU VOIS',
  'type.matchTranslation': 'ASSOCIE',
  'type.match': 'ASSOCIE',
  'type.inputListenGaps': 'COMPLÈTE',
  'type.inputListenWrite': 'ÉCRIS CE QUE TU ENTENDS',
  'type.matchAudio': 'ASSOCIE LES SONS',
  'type.inputTranslation': 'ÉCRIS LA TRADUCTION',
  'type.arrangeTranslation': 'CONSTRUIS LA TRADUCTION',
  'type.selectContext': 'CONTEXTE',
  'instruction.default': 'Fais l’exercice.',
  'instruction.inputMissingWord':
      'La première lettre est donnée : écris le mot entier.',
  'instruction.selectCharacter':
      'Choisis l’option qui correspond au caractère.',
  'instruction.select': 'Trouve la bonne réponse.',
  'instruction.selectListen':
      'Trouve la réponse qui correspond à ce que tu entends.',
  'instruction.selectListenPassage': 'Écoute et choisis la bonne réponse.',
  'instruction.selectRead': 'Lis et choisis la bonne réponse.',
  'instruction.selectDialogue':
      'Lis le dialogue et choisis la meilleure réponse.',
  'instruction.selectImage': 'Trouve l’image qui correspond.',
  'instruction.presentation': 'Étudie le mot et son usage.',
  'instruction.dialogueLine': 'Lis ou écoute, puis continue.',
  'instruction.dialogueLineText': 'Lis, puis continue.',
  'instruction.dialogueLineAudio': 'Écoute, puis continue.',
  'instruction.dialogueLineAfterAudio':
      'Écoute d’abord ; le texte apparaît ensuite.',
  'instruction.storyCover': 'Une histoire commence. Continue quand tu veux.',
  'instruction.inputComplete': 'Écris les mots qui complètent la phrase.',
  'instruction.selectComplete': 'Choisis le bloc qui remplit le vide.',
  'instruction.select_opposite': 'Trouve le contraire.',
  'instruction.arrangeSentence': 'Mets les mots dans le bon ordre.',
  'instruction.arrangeLines': 'Range les lignes dans un ordre logique.',
  'instruction.arrangeWord': 'Épelle ce que montre l’image.',
  'instruction.inputPictureName': 'Écris le nom de l’image.',
  'instruction.arrangePictureName':
      'Mets les blocs dans l’ordre pour nommer l’image.',
  'instruction.matchTranslation': 'Associe chaque mot à sa traduction.',
  'instruction.match': 'Associe les éléments qui vont ensemble.',
  'type.assignGroups': 'TRIE PAR GROUPES',
  'type.assignSlots': 'REMPLIS LES CASES',
  'type.assignGaps': 'REMPLIS LES TROUS',
  'instruction.assignGroups':
      'Touche un élément, puis le groupe auquel il appartient.',
  'instruction.assignSlots': 'Touche un élément, puis sa case.',
  'instruction.assignGaps': 'Touche un mot, puis le trou qu’il remplit.',
  'instruction.inputListenGaps': 'Écoute et complète le mot manquant.',
  'instruction.inputListenWrite': 'Écris chaque mot que tu entends.',
  'instruction.matchAudio': 'Associe chaque son à son mot.',
  'instruction.inputTranslation': 'Traduis en {language}.',
  'instruction.arrangeTranslation':
      'Traduis en {language} avec les blocs de mots.',
  'instruction.selectContext':
      'Utilise le contexte pour choisir la bonne réponse.',
  'instruction.inputCompleteOne': 'Écris le mot qui complète la phrase.',
  'instruction.inputCompleteLetters': 'Écris les lettres manquantes.',
  'instruction.selectListenQuestion': 'Écoute et réponds à la question.',
  'instruction.selectListenHeard': 'Choisis la phrase que tu as entendue.',
  'instruction.selectListenMeaning': 'Choisis le sens de ce que tu as entendu.',
  'type.selectPicture': 'QU’Y A-T-IL SUR L’IMAGE ?',
  'instruction.selectPicture': 'Choisis l’option qui convient le mieux.',
  'instruction.arrangeWordHeard': 'Épelle le mot que tu entends.',
  'instruction.arrangeWordClue': 'Épelle le mot que l’indice décrit.',
  'instruction.arrangeGaps': 'Choisis un mot pour chaque trou.',
  'type.selectCompleteAll': 'UN MOT POUR TOUS LES TROUS',
  'instruction.selectCompleteAll': 'Choisis le mot qui remplit tous les trous.',
};
