/// The Italian exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyIt = <String, String>{
  'type.default': 'ESERCIZIO',
  'type.inputMissingWord': 'SCRIVI LA PAROLA MANCANTE',
  'type.selectCharacter': 'RICONOSCI I CARATTERI',
  'type.select': 'SCEGLI',
  'type.selectListen': 'ASCOLTA E SCEGLI',
  'type.selectListenPassage': 'ASCOLTO',
  'type.selectRead': 'LETTURA',
  'type.selectDialogue': 'DIALOGO',
  'type.selectImage': 'SCEGLI L’IMMAGINE',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOGO',
  'type.storyCover': 'STORIA',
  'type.inputComplete': 'COMPLETA',
  'type.selectComplete': 'COMPLETA LA FRASE',
  'type.arrangeSentence': 'COMPONI LA FRASE',
  'type.arrangeLines': 'ORDINA LE FRASI',
  'type.arrangeWord': 'COMPONI LA PAROLA',
  'type.inputPictureName': 'NOMINA CIÒ CHE VEDI',
  'type.arrangePictureName': 'NOMINA CIÒ CHE VEDI',
  'type.matchTranslation': 'ABBINA',
  'type.match': 'ABBINA',
  'type.inputListenGaps': 'COMPLETA',
  'type.inputListenWrite': 'SCRIVI CIÒ CHE SENTI',
  'type.matchAudio': 'ABBINA L’AUDIO',
  'instruction.default': 'Completa l’esercizio.',
  'instruction.inputMissingWord':
      'La prima lettera è data: scrivi la parola intera.',
  'instruction.selectCharacter':
      'Scegli l’opzione che corrisponde al carattere.',
  'instruction.select': 'Trova la risposta corretta.',
  'instruction.selectListen':
      'Trova la risposta che corrisponde a ciò che senti.',
  'instruction.selectListenPassage': 'Ascolta e scegli la risposta corretta.',
  'instruction.selectRead': 'Leggi e scegli la risposta corretta.',
  'instruction.selectDialogue':
      'Leggi il dialogo e scegli la risposta migliore.',
  'instruction.selectImage': 'Trova l’immagine corrispondente.',
  'instruction.presentation': 'Studia la parola e il suo uso.',
  'instruction.dialogueLine': 'Leggi o ascolta, poi continua.',
  'instruction.dialogueLineText': 'Leggi, poi continua.',
  'instruction.dialogueLineAudio': 'Ascolta, poi continua.',
  'instruction.dialogueLineAfterAudio': 'Ascolta prima; il testo compare dopo.',
  'instruction.storyCover': 'Inizia una storia. Continua quando sei pronto.',
  'instruction.inputComplete': 'Scrivi le parole che completano la frase.',
  'instruction.selectComplete': 'Scegli il blocco adatto allo spazio vuoto.',
  'instruction.select_opposite': 'Trova il contrario.',
  'instruction.arrangeSentence': 'Metti le parole nell’ordine corretto.',
  'instruction.arrangeLines': 'Metti le righe in un ordine logico.',
  'instruction.arrangeWord': 'Compita ciò che mostra l’immagine.',
  'instruction.inputPictureName': 'Scrivi il nome dell’immagine.',
  'instruction.arrangePictureName':
      'Metti in ordine i blocchi per dare il nome all’immagine.',
  'instruction.matchTranslation': 'Accoppia ogni parola alla sua traduzione.',
  'instruction.match': 'Accoppia gli elementi che vanno insieme.',
  'type.assignGroups': 'SMISTA IN GRUPPI',
  'type.assignSlots': 'RIEMPI LE CASELLE',
  'type.assignGaps': 'RIEMPI GLI SPAZI',
  'instruction.assignGroups':
      'Tocca un elemento, poi il gruppo a cui appartiene.',
  'instruction.assignSlots': 'Tocca un elemento, poi la sua casella.',
  'instruction.assignGaps': 'Tocca una parola, poi lo spazio che riempie.',
  'instruction.inputListenGaps': 'Ascolta e completa la parola mancante.',
  'instruction.inputListenWrite': 'Scrivi ogni parola che senti.',
  'instruction.matchAudio': 'Accoppia ogni audio alla sua parola.',
  'type.inputTranslation': 'SCRIVI LA TRADUZIONE',
  'type.arrangeTranslation': 'COMPONI LA TRADUZIONE',
  'type.selectContext': 'CONTESTO',
  'instruction.inputTranslation': 'Traduci in {language}.',
  'instruction.arrangeTranslation':
      'Traduci in {language} con i blocchi di parole.',
  'instruction.selectContext':
      'Usa il contesto per scegliere la risposta corretta.',
  'instruction.inputCompleteOne': 'Scrivi la parola che completa la frase.',
  'instruction.inputCompleteLetters': 'Scrivi le lettere mancanti.',
  'instruction.selectListenQuestion': 'Ascolta e rispondi alla domanda.',
  'instruction.selectListenHeard': 'Seleziona la frase che hai sentito.',
  'instruction.selectListenMeaning':
      'Seleziona il significato di ciò che hai sentito.',
  'type.selectPicture': 'COSA C’È NELL’IMMAGINE?',
  'instruction.selectPicture': 'Scegli l’opzione più adatta.',
  'instruction.arrangeWordHeard': 'Compita la parola che senti.',
  'instruction.arrangeWordClue': 'Compita la parola descritta dall’indizio.',
  'instruction.arrangeGaps': 'Scegli una parola per ogni spazio.',
  'type.selectCompleteAll': 'UNA PAROLA PER TUTTI',
  'instruction.selectCompleteAll':
      'Scegli la parola che completa tutti gli spazi.',
};
