/// The Italian exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyIt = <String, String>{
  'type.default': 'ESERCIZIO',
  'type.inputMissingWord': 'SCRIVI LA PAROLA MANCANTE',
  'type.selectCharacter': 'RICONOSCI I CARATTERI',
  'type.select': 'SCEGLI',
  'type.selectListen': 'ASCOLTA E SCEGLI',
  'type.selectListenPassage': 'ASCOLTO',
  'type.selectRead': 'LETTURA',
  'type.selectDialogue': 'DIALOGO',
  'type.selectImage': 'SCEGLI L’IMMAGINE',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOGO',
  'type.storyCover': 'STORIA',
  'type.inputComplete': 'COMPLETA',
  'type.selectComplete': 'COMPLETA LA FRASE',
  'type.arrangeSentence': 'COMPONI LA FRASE',
  'type.arrangeLines': 'ORDINA LE FRASI',
  'type.arrangeWord': 'COMPONI LA PAROLA',
  'type.inputPictureName': 'NOMINA CIÒ CHE VEDI',
  'type.arrangePictureName': 'NOMINA CIÒ CHE VEDI',
  'type.matchTranslation': 'ABBINA',
  'type.match': 'ABBINA',
  'type.inputListenGaps': 'COMPLETA',
  'type.inputListenWrite': 'SCRIVI CIÒ CHE SENTI',
  'type.matchAudio': 'ABBINA L’AUDIO',
  'instruction.default': 'Completa l’esercizio.',
  'instruction.inputMissingWord':
      'La prima lettera è data: scrivi la parola intera.',
  'instruction.selectCharacter':
      'Scegli l’opzione che corrisponde al carattere.',
  'instruction.select': 'Trova la risposta corretta.',
  'instruction.selectListen':
      'Trova la risposta che corrisponde a ciò che senti.',
  'instruction.selectListenPassage': 'Ascolta e scegli la risposta corretta.',
  'instruction.selectRead': 'Leggi e scegli la risposta corretta.',
  'instruction.selectDialogue':
      'Leggi il dialogo e scegli la risposta migliore.',
  'instruction.selectImage': 'Trova l’immagine corrispondente.',
  'instruction.presentation': 'Studia la parola e il suo uso.',
  'instruction.dialogueLine': 'Leggi o ascolta, poi continua.',
  'instruction.dialogueLineText': 'Leggi, poi continua.',
  'instruction.dialogueLineAudio': 'Ascolta, poi continua.',
  'instruction.dialogueLineAfterAudio': 'Ascolta prima; il testo compare dopo.',
  'instruction.storyCover': 'Inizia una storia. Continua quando sei pronto.',
  'instruction.inputComplete': 'Scrivi le parole che completano la frase.',
  'instruction.selectComplete': 'Scegli il blocco adatto allo spazio vuoto.',
  'instruction.select_opposite': 'Trova il contrario.',
  'instruction.arrangeSentence': 'Metti le parole nell’ordine corretto.',
  'instruction.arrangeLines': 'Metti le righe in un ordine logico.',
  'instruction.arrangeWord': 'Compita ciò che mostra l’immagine.',
  'instruction.inputPictureName': 'Scrivi il nome dell’immagine.',
  'instruction.arrangePictureName':
      'Metti in ordine i blocchi per dare il nome all’immagine.',
  'instruction.matchTranslation': 'Accoppia ogni parola alla sua traduzione.',
  'instruction.match': 'Accoppia gli elementi che vanno insieme.',
  'type.assignGroups': 'SMISTA IN GRUPPI',
  'type.assignSlots': 'RIEMPI LE CASELLE',
  'type.assignGaps': 'RIEMPI GLI SPAZI',
  'instruction.assignGroups':
      'Tocca un elemento, poi il gruppo a cui appartiene.',
  'instruction.assignSlots': 'Tocca un elemento, poi la sua casella.',
  'instruction.assignGaps': 'Tocca una parola, poi lo spazio che riempie.',
  'instruction.inputListenGaps': 'Ascolta e completa la parola mancante.',
  'instruction.inputListenWrite': 'Scrivi ogni parola che senti.',
  'instruction.matchAudio': 'Accoppia ogni audio alla sua parola.',
  'type.inputTranslation': 'SCRIVI LA TRADUZIONE',
  'type.arrangeTranslation': 'COMPONI LA TRADUZIONE',
  'type.selectContext': 'CONTESTO',
  'instruction.inputTranslation': 'Traduci in {language}.',
  'instruction.arrangeTranslation':
      'Traduci in {language} con i blocchi di parole.',
  'instruction.selectContext':
      'Usa il contesto per scegliere la risposta corretta.',
  'instruction.inputCompleteOne': 'Scrivi la parola che completa la frase.',
  'instruction.inputCompleteLetters': 'Scrivi le lettere mancanti.',
  'instruction.selectListenQuestion': 'Ascolta e rispondi alla domanda.',
  'instruction.selectListenHeard': 'Seleziona la frase che hai sentito.',
  'instruction.selectListenMeaning':
      'Seleziona il significato di ciò che hai sentito.',
  'type.selectPicture': 'COSA C’È NELL’IMMAGINE?',
  'instruction.selectPicture': 'Scegli l’opzione più adatta.',
  'instruction.arrangeWordHeard': 'Compita la parola che senti.',
  'instruction.arrangeWordClue': 'Compita la parola descritta dall’indizio.',
  'instruction.arrangeGaps': 'Scegli una parola per ogni spazio.',
  'type.selectCompleteAll': 'UNA PAROLA PER TUTTI',
  'instruction.selectCompleteAll':
      'Scegli la parola che completa tutti gli spazi.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'SCEGLI LA TRADUZIONE',
  'title.type_the_translation': 'SCRIVI LA TRADUZIONE',
  'title.build_the_translation': 'COMPONI LA TRADUZIONE',
  'title.match_the_words': 'ABBINA LE PAROLE',
  'title.match_by_meaning': 'ABBINA PER SIGNIFICATO',
  'title.flashcard': 'FLASHCARD',
  'title.picture_flashcard': 'FLASHCARD CON IMMAGINE',
  'title.choose_the_answer': 'SCEGLI LA RISPOSTA',
  'title.pick_the_missing_word': 'SCEGLI LA PAROLA MANCANTE',
  'title.type_the_missing_word': 'SCRIVI LA PAROLA MANCANTE',
  'title.word_order': 'ORDINE DELLE PAROLE',
  'title.true_or_false': 'VERO O FALSO',
  'title.pick_the_words_for_the_gaps': 'SCEGLI LE PAROLE PER GLI SPAZI',
  'title.one_word_fills_all': 'UNA PAROLA PER TUTTI',
  'title.complete_the_text': 'COMPLETA IL TESTO',
  'title.missing_letters': 'LETTERE MANCANTI',
  'title.put_the_sentences_in_order': 'ORDINA LE FRASI',
  'title.sort_into_groups': 'SMISTA IN GRUPPI',
  'title.fill_the_slots': 'RIEMPI LE CASELLE',
  'title.listen_and_choose': 'ASCOLTA E SCEGLI',
  'title.listen_and_answer': 'ASCOLTA E RISPONDI',
  'title.type_what_you_hear': 'SCRIVI CIÒ CHE SENTI',
  'title.listen_and_fill_the_gaps': 'ASCOLTA E RIEMPI GLI SPAZI',
  'title.listen_and_match': 'ASCOLTA E ABBINA',
  'title.listen_and_pick_the_image': 'ASCOLTA E SCEGLI L’IMMAGINE',
  'title.spell_what_you_hear': 'COMPONI CIÒ CHE SENTI',
  'title.read_and_answer': 'LEGGI E RISPONDI',
  'title.select_the_image': 'SCEGLI L’IMMAGINE',
  'title.recognize_characters': 'RICONOSCI I CARATTERI',
  'title.spell_the_word_in_the_picture': 'COMPONI LA PAROLA DELL’IMMAGINE',
  'title.what_is_in_the_picture': 'COSA C’È NELL’IMMAGINE?',
  'title.type_what_you_see': 'SCRIVI CIÒ CHE VEDI',
  'title.name_what_you_see': 'NOMINA CIÒ CHE VEDI',
  'title.spell_the_word': 'COMPONI LA PAROLA',
  'title.match_pictures_to_words': 'ABBINA IMMAGINI E PAROLE',
  'title.note_card': 'NOTA',
  'title.dialogue_line': 'BATTUTA',
  'title.story_cover': 'COPERTINA DELLA STORIA',
  'title.before_you_start': 'PRIMA DI INIZIARE',
  'title.page': 'PAGINA',
  'instruction.selectTranslation':
      'Scegli la traduzione corretta in {language}',
};
