/// The English exercise headings and instruction lines of the learner
/// panel (moved from ExerciseCopyService in Build 260 Revision 0).
const exerciseCopyEn = <String, String>{
  'type.default': 'EXERCISE',
  'type.inputMissingWord': 'TYPE THE MISSING WORD',
  'type.selectCharacter': 'RECOGNIZE CHARACTERS',
  'type.select': 'CHOOSE',
  'type.selectListen': 'LISTEN AND CHOOSE',
  'type.selectListenPassage': 'LISTENING',
  'type.selectRead': 'READING',
  'type.selectDialogue': 'DIALOGUE',
  'type.selectImage': 'CHOOSE THE IMAGE',
  'type.presentation': 'FLASHCARD',
  'type.dialogueLine': 'DIALOGUE',
  'type.storyCover': 'STORY',
  'type.inputComplete': 'COMPLETE',
  'type.selectComplete': 'COMPLETE THE SENTENCE',
  'type.arrangeSentence': 'BUILD THE SENTENCE',
  'type.arrangeLines': 'PUT THE SENTENCES IN ORDER',
  'type.arrangeWord': 'BUILD THE WORD',
  'type.inputPictureName': 'NAME WHAT YOU SEE',
  'type.arrangePictureName': 'NAME WHAT YOU SEE',
  'type.matchTranslation': 'MATCH',
  'type.match': 'MATCH',
  'type.inputListenGaps': 'COMPLETE',
  'type.inputListenWrite': 'WRITE WHAT YOU HEAR',
  'type.matchAudio': 'MATCH THE AUDIO',
  'type.inputTranslation': 'TYPE THE TRANSLATION',
  'type.arrangeTranslation': 'BUILD THE TRANSLATION',
  'type.selectContext': 'CONTEXT',
  'instruction.default': 'Complete the exercise.',
  'instruction.inputMissingWord':
      'The first letter is given: type the whole word.',
  'instruction.selectCharacter':
      'Choose the option that matches the character.',
  'instruction.select': 'Find the correct answer.',
  'instruction.selectListen': 'Find the answer that matches what you hear.',
  'instruction.selectListenPassage': 'Listen and choose the correct answer.',
  'instruction.selectRead': 'Read and choose the correct answer.',
  'instruction.selectDialogue':
      'Read the dialogue and choose the best response.',
  'instruction.selectImage': 'Find the matching picture.',
  'instruction.presentation': 'Study the word and its usage.',
  'instruction.dialogueLine': 'Read or listen, then continue.',
  'instruction.dialogueLineText': 'Read, then continue.',
  'instruction.dialogueLineAudio': 'Listen, then continue.',
  'instruction.dialogueLineAfterAudio': 'Listen first; the text appears after.',
  'instruction.storyCover': 'A story begins. Continue when you are ready.',
  'instruction.inputComplete': 'Type the words that complete the sentence.',
  'instruction.selectComplete': 'Pick the block that fits the gap.',
  'instruction.select_opposite': 'Find the opposite.',
  'instruction.arrangeSentence': 'Put the words in the correct order.',
  'instruction.arrangeLines': 'Arrange the lines in a logical order.',
  'instruction.arrangeWord': 'Spell what the picture shows.',
  'instruction.inputPictureName': 'Type the name of the picture.',
  'instruction.arrangePictureName':
      'Put the blocks in order to name the picture.',
  'instruction.matchTranslation': 'Pair each word with its translation.',
  'instruction.match': 'Pair the items that belong together.',
  'type.assignGroups': 'SORT INTO GROUPS',
  'type.assignSlots': 'FILL THE SLOTS',
  'type.assignGaps': 'FILL THE GAPS',
  'instruction.assignGroups': 'Tap an item, then the group it belongs to.',
  'instruction.assignSlots': 'Tap an item, then its slot.',
  'instruction.assignGaps': 'Tap a word, then the gap it fills.',
  'instruction.inputListenGaps': 'Listen and complete the missing word.',
  'instruction.inputListenWrite': 'Type every word you hear.',
  'instruction.matchAudio': 'Pair each sound with its word.',
  'instruction.inputTranslation': 'Translate into {language}.',
  'instruction.arrangeTranslation':
      'Translate into {language} with the word blocks.',
  'instruction.selectContext': 'Use the context to choose the correct answer.',
  'instruction.inputCompleteOne': 'Type the word that completes the sentence.',
  'instruction.inputCompleteLetters': 'Type the missing letters.',
  'instruction.selectListenQuestion': 'Listen and answer the question.',
  'instruction.selectListenHeard': 'Select the sentence that you heard.',
  'instruction.selectListenMeaning': 'Select the meaning of what you heard.',
  'type.selectPicture': 'WHAT IS IN THE PICTURE?',
  'instruction.selectPicture': 'Choose the option that fits best.',
  'instruction.arrangeWordHeard': 'Spell the word you hear.',
  'instruction.arrangeWordClue': 'Spell the word the clue describes.',
  'instruction.arrangeGaps': 'Pick a word for each gap.',
  'type.selectCompleteAll': 'ONE WORD FILLS ALL',
  'instruction.selectCompleteAll': 'Choose the word that fills every gap.',
};
