/// The French exercise headings and instruction lines of the learner panel
/// (Build 260 Revision 0, owner decision of 1 October 2026). AI-written,
/// pending native review.
const exerciseCopyFr = <String, String>{
  'type.default': 'EXERCICE',
  'type.inputMissingWord': 'ÉCRIS LE MOT MANQUANT',
  'type.selectCharacter': 'RECONNAIS LES CARACTÈRES',
  'type.select': 'CHOISIS',
  'type.selectListen': 'ÉCOUTE ET CHOISIS',
  'type.selectListenPassage': 'COMPRÉHENSION ORALE',
  'type.selectRead': 'LECTURE',
  'type.selectDialogue': 'DIALOGUE',
  'type.selectImage': 'CHOISIS L’IMAGE',
  'type.presentation': 'CARTE',
  'type.dialogueLine': 'DIALOGUE',
  'type.storyCover': 'HISTOIRE',
  'type.inputComplete': 'COMPLÈTE',
  'type.selectComplete': 'COMPLÈTE LA PHRASE',
  'type.arrangeSentence': 'CONSTRUIS LA PHRASE',
  'type.arrangeLines': 'METS LES PHRASES DANS L’ORDRE',
  'type.arrangeWord': 'CONSTRUIS LE MOT',
  'type.inputPictureName': 'NOMME CE QUE TU VOIS',
  'type.arrangePictureName': 'NOMME CE QUE TU VOIS',
  'type.matchTranslation': 'ASSOCIE',
  'type.match': 'ASSOCIE',
  'type.inputListenGaps': 'COMPLÈTE',
  'type.inputListenWrite': 'ÉCRIS CE QUE TU ENTENDS',
  'type.matchAudio': 'ASSOCIE LES SONS',
  'type.inputTranslation': 'ÉCRIS LA TRADUCTION',
  'type.arrangeTranslation': 'CONSTRUIS LA TRADUCTION',
  'type.selectContext': 'CONTEXTE',
  'instruction.default': 'Fais l’exercice.',
  'instruction.inputMissingWord':
      'La première lettre est donnée : écris le mot entier.',
  'instruction.selectCharacter':
      'Choisis l’option qui correspond au caractère.',
  'instruction.select': 'Trouve la bonne réponse.',
  'instruction.selectListen':
      'Trouve la réponse qui correspond à ce que tu entends.',
  'instruction.selectListenPassage': 'Écoute et choisis la bonne réponse.',
  'instruction.selectRead': 'Lis et choisis la bonne réponse.',
  'instruction.selectDialogue':
      'Lis le dialogue et choisis la meilleure réponse.',
  'instruction.selectImage': 'Trouve l’image qui correspond.',
  'instruction.presentation': 'Étudie le mot et son usage.',
  'instruction.dialogueLine': 'Lis ou écoute, puis continue.',
  'instruction.dialogueLineText': 'Lis, puis continue.',
  'instruction.dialogueLineAudio': 'Écoute, puis continue.',
  'instruction.dialogueLineAfterAudio':
      'Écoute d’abord ; le texte apparaît ensuite.',
  'instruction.storyCover': 'Une histoire commence. Continue quand tu veux.',
  'instruction.inputComplete': 'Saisis les mots qui manquent dans la phrase.',
  'instruction.selectComplete': 'Sélectionne le bloc qui remplit le vide.',
  'instruction.select_opposite': 'Trouve le contraire.',
  'instruction.arrangeSentence': 'Range les mots dans le bon ordre.',
  'instruction.arrangeLines': 'Range les lignes dans un ordre logique.',
  'instruction.arrangeWord': 'Forme le mot que montre l’image.',
  'instruction.inputPictureName': 'Saisis le nom de l’image.',
  'instruction.arrangePictureName':
      'Mets les blocs dans l’ordre pour nommer l’image.',
  'instruction.matchTranslation': 'Relie chaque mot à sa traduction.',
  'instruction.match': 'Relie les éléments qui vont ensemble.',
  'type.assignGroups': 'TRIE PAR GROUPES',
  'type.assignSlots': 'REMPLIS LES CASES',
  'type.assignGaps': 'REMPLIS LES TROUS',
  'instruction.assignGroups':
      'Touche un élément, puis le groupe auquel il appartient.',
  'instruction.assignSlots': 'Touche un élément, puis sa case.',
  'instruction.assignGaps': 'Touche un mot, puis le trou qu’il remplit.',
  'instruction.inputListenGaps': 'Saisis le mot manquant que tu entends.',
  'instruction.inputListenWrite': 'Transcris chaque mot que tu entends.',
  'instruction.matchAudio': 'Relie chaque son à son mot.',
  'instruction.inputTranslation': 'Traduis en {language}.',
  'instruction.arrangeTranslation':
      'Traduis en {language} avec les blocs de mots.',
  'instruction.selectContext':
      'Utilise le contexte pour choisir la bonne réponse.',
  'instruction.inputCompleteOne': 'Saisis le mot qui manque dans la phrase.',
  'instruction.inputCompleteLetters': 'Saisis les lettres manquantes.',
  'instruction.selectListenQuestion':
      'Réponds à la question sur ce que tu entends.',
  'instruction.selectListenHeard': 'Choisis la phrase que tu as entendue.',
  'instruction.selectListenMeaning': 'Choisis le sens de ce que tu as entendu.',
  'type.selectPicture': 'QU’Y A-T-IL SUR L’IMAGE ?',
  'instruction.selectPicture': 'Choisis l’option qui convient le mieux.',
  'instruction.arrangeWordHeard': 'Forme le mot que tu entends.',
  'instruction.arrangeWordClue': 'Forme le mot que l’indice décrit.',
  'instruction.arrangeGaps': 'Place un mot dans chaque trou.',
  'type.selectCompleteAll': 'UN MOT POUR TOUS LES TROUS',
  'instruction.selectCompleteAll': 'Choisis le mot qui remplit tous les trous.',
  // Exercise titles: the preset names (Build 261 Revision 3, owner
  // decisions of 2 October 2026).
  'title.pick_the_translation': 'CHOISIS LA TRADUCTION',
  'title.type_the_translation': 'ÉCRIS LA TRADUCTION',
  'title.build_the_translation': 'CONSTRUIS LA TRADUCTION',
  'title.match_the_words': 'ASSOCIE LES MOTS',
  'title.match_by_meaning': 'ASSOCIE PAR LE SENS',
  'title.flashcard': 'CARTE',
  'title.picture_flashcard': 'CARTE ILLUSTRÉE',
  'title.choose_the_answer': 'CHOISIS LA RÉPONSE',
  'title.pick_the_missing_word': 'CHOISIS LE MOT MANQUANT',
  'title.type_the_missing_word': 'ÉCRIS LE MOT MANQUANT',
  'title.word_order': 'ORDRE DES MOTS',
  'title.true_or_false': 'VRAI OU FAUX',
  'title.pick_the_words_for_the_gaps': 'CHOISIS LES MOTS POUR LES TROUS',
  'title.one_word_fills_all': 'UN MOT POUR TOUS LES TROUS',
  'title.complete_the_text': 'COMPLÈTE LE TEXTE',
  'title.missing_letters': 'LETTRES MANQUANTES',
  'title.put_the_sentences_in_order': 'METS LES PHRASES DANS L’ORDRE',
  'title.sort_into_groups': 'TRIE PAR GROUPES',
  'title.fill_the_slots': 'REMPLIS LES CASES',
  'title.listen_and_choose': 'ÉCOUTE ET CHOISIS',
  'title.listen_and_answer': 'ÉCOUTE ET RÉPONDS',
  'title.type_what_you_hear': 'ÉCRIS CE QUE TU ENTENDS',
  'title.listen_and_fill_the_gaps': 'ÉCOUTE ET REMPLIS LES TROUS',
  'title.listen_and_match': 'ÉCOUTE ET ASSOCIE',
  'title.listen_and_pick_the_image': 'ÉCOUTE ET CHOISIS L’IMAGE',
  'title.spell_what_you_hear': 'ÉPELLE CE QUE TU ENTENDS',
  'title.read_and_answer': 'LIS ET RÉPONDS',
  'title.select_the_image': 'CHOISIS L’IMAGE',
  'title.recognize_characters': 'RECONNAIS LES CARACTÈRES',
  'title.spell_the_word_in_the_picture': 'ÉPELLE LE MOT DE L’IMAGE',
  'title.what_is_in_the_picture': 'QU’Y A-T-IL SUR L’IMAGE ?',
  'title.type_what_you_see': 'ÉCRIS CE QUE TU VOIS',
  'title.name_what_you_see': 'NOMME CE QUE TU VOIS',
  'title.spell_the_word': 'ÉPELLE LE MOT',
  'title.match_pictures_to_words': 'ASSOCIE IMAGES ET MOTS',
  'title.note_card': 'FICHE NOTE',
  'title.dialogue_line': 'RÉPLIQUE',
  'title.story_cover': 'COUVERTURE DE L’HISTOIRE',
  'title.before_you_start': 'AVANT DE COMMENCER',
  'title.page': 'PAGE',
  'instruction.selectTranslation':
      'Sélectionne la bonne traduction en {language}',
};
