name: quisquislingo_flutter_tts_windows
description: Windows-only no-op flutter_tts implementation for QuisquisLingo.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_tts
    platforms:
      windows:
        dartPluginClass: QuisquisLingoFlutterTtsWindows
